import { defineStrings } from "@/site/i18n/strings";

// Web-only strings of Settings and «О материалах» (spec 02 §8, web deltas spec 09 G11).
// App strings («Язык», «Оформление», «Открыть Plus», …) come from the app packs through t().

export const settingsStrings = defineStrings({
  ru: {
    description: "Plus, аккаунт, язык и оформление inApp.",
    account: "Аккаунт",
    signInRestore: "Войти, чтобы восстановить доступ",
    signOut: "Выйти",
    signOutFailed: "Не получилось выйти. Попробуй ещё раз.",
    restoreActive: "Plus активен в этом аккаунте.",
    restoreNone: "В этом аккаунте покупок не нашлось.",
    restoreFailed: "Не удалось проверить доступ. Попробуй ещё раз.",
    iphoneApp: "Приложение для iPhone",
    paymentOffer: "Оферта",
    storedBrowser: "Закладки и заметки хранятся в этом браузере.",
    storedAccount: "Закладки и заметки хранятся в твоём аккаунте.",
    recordsBrowser:
      "Закладки и заметки хранятся в этом браузере. Удаление закладки не удаляет заметку. Синхронизации между устройствами нет.",
    recordsAccount:
      "Закладки и заметки хранятся в твоём аккаунте и доступны после входа на любом устройстве. Удаление закладки не удаляет заметку.",
    aboutDescription: "Из чего составлены разборы и идеи inApp, что доступно бесплатно и где хранятся твои записи.",
    // «Удалить аккаунт» (signed in only): POST /api/site/account/delete {confirm:"DELETE"}.
    deleteAccount: "Удалить аккаунт",
    deleteTitle: "Удалить аккаунт?",
    deleteBody: "Аккаунт удалится вместе с закладками, заметками и историей просмотров. Отменить это нельзя.",
    deletePurchases: "Покупки, привязанные к аккаунту, пропадут: доступ Plus, оплаченный на сайте, вернуть не получится.",
    deleteAppStore: "Подписка из App Store от этого не отменится — ею управляют в настройках Apple ID.",
    deleteConfirmLabel: "Чтобы подтвердить, введи {word}",
    deleteWord: "УДАЛИТЬ",
    deleteSubmit: "Удалить навсегда",
    deleteBusy: "Удаляем…",
    deleteFailed: "Не получилось удалить аккаунт. Попробуй ещё раз или напиши нам.",
  },
  en: {
    description: "Plus, account, language and appearance of inApp.",
    account: "Account",
    signInRestore: "Sign in to restore access",
    signOut: "Sign out",
    signOutFailed: "Couldn’t sign out. Try again.",
    restoreActive: "Plus is active in this account.",
    restoreNone: "No purchases found in this account.",
    restoreFailed: "Couldn’t check your access. Try again.",
    iphoneApp: "The iPhone app",
    paymentOffer: "Public offer",
    storedBrowser: "Bookmarks and notes are kept in this browser.",
    storedAccount: "Bookmarks and notes are kept in your account.",
    recordsBrowser:
      "Bookmarks and notes are kept in this browser. Removing a bookmark does not delete the note. There is no syncing between devices.",
    recordsAccount:
      "Bookmarks and notes are kept in your account and are available on any device once you sign in. Removing a bookmark does not delete the note.",
    aboutDescription: "What inApp’s breakdowns and ideas are built from, what is free and where your records are kept.",
    deleteAccount: "Delete account",
    deleteTitle: "Delete your account?",
    deleteBody: "Your account will be deleted together with its bookmarks, notes and page history. This can’t be undone.",
    deletePurchases: "Purchases tied to the account will be lost: Plus access paid for on the website can’t be restored.",
    deleteAppStore: "This doesn’t cancel an App Store subscription — you manage that in your Apple ID settings.",
    deleteConfirmLabel: "To confirm, type {word}",
    deleteWord: "DELETE",
    deleteSubmit: "Delete forever",
    deleteBusy: "Deleting…",
    deleteFailed: "Couldn’t delete the account. Try again or write to us.",
  },
  de: {
    description: "Plus, Konto, Sprache und Darstellung von inApp.",
    account: "Konto",
    signInRestore: "Anmelden, um den Zugang wiederherzustellen",
    signOut: "Abmelden",
    signOutFailed: "Abmelden hat nicht geklappt. Versuch es noch einmal.",
    restoreActive: "Plus ist in diesem Konto aktiv.",
    restoreNone: "In diesem Konto wurden keine Käufe gefunden.",
    restoreFailed: "Dein Zugang ließ sich nicht prüfen. Versuch es noch einmal.",
    iphoneApp: "Die iPhone-App",
    paymentOffer: "Öffentliches Angebot",
    storedBrowser: "Lesezeichen und Notizen bleiben in diesem Browser.",
    storedAccount: "Lesezeichen und Notizen liegen in deinem Konto.",
    recordsBrowser:
      "Lesezeichen und Notizen bleiben in diesem Browser. Ein entferntes Lesezeichen löscht die Notiz nicht. Zwischen Geräten wird nichts synchronisiert.",
    recordsAccount:
      "Lesezeichen und Notizen liegen in deinem Konto und sind nach der Anmeldung auf jedem Gerät verfügbar. Ein entferntes Lesezeichen löscht die Notiz nicht.",
    aboutDescription: "Woraus die Analysen und Ideen von inApp bestehen, was kostenlos ist und wo deine Einträge liegen.",
    deleteAccount: "Konto löschen",
    deleteTitle: "Konto löschen?",
    deleteBody: "Dein Konto wird samt Lesezeichen, Notizen und Seitenverlauf gelöscht. Das lässt sich nicht rückgängig machen.",
    deletePurchases: "Käufe, die an das Konto gebunden sind, gehen verloren: Auf der Website bezahltes Plus lässt sich nicht wiederherstellen.",
    deleteAppStore: "Ein App-Store-Abo wird dadurch nicht gekündigt – das verwaltest du in den Einstellungen deiner Apple-ID.",
    deleteConfirmLabel: "Gib zur Bestätigung {word} ein",
    deleteWord: "LÖSCHEN",
    deleteSubmit: "Endgültig löschen",
    deleteBusy: "Wird gelöscht…",
    deleteFailed: "Das Konto ließ sich nicht löschen. Versuch es noch einmal oder schreib uns.",
  },
  fr: {
    description: "Plus, compte, langue et apparence d’inApp.",
    account: "Compte",
    signInRestore: "Se connecter pour restaurer l’accès",
    signOut: "Se déconnecter",
    signOutFailed: "Impossible de se déconnecter. Réessaie.",
    restoreActive: "Plus est actif sur ce compte.",
    restoreNone: "Aucun achat trouvé sur ce compte.",
    restoreFailed: "Impossible de vérifier ton accès. Réessaie.",
    iphoneApp: "L’app pour iPhone",
    paymentOffer: "Offre publique",
    storedBrowser: "Les signets et les notes restent dans ce navigateur.",
    storedAccount: "Les signets et les notes sont dans ton compte.",
    recordsBrowser:
      "Les signets et les notes restent dans ce navigateur. Retirer un signet ne supprime pas la note. Il n’y a pas de synchronisation entre appareils.",
    recordsAccount:
      "Les signets et les notes sont dans ton compte et disponibles sur n’importe quel appareil une fois connecté. Retirer un signet ne supprime pas la note.",
    aboutDescription: "De quoi sont faits les décryptages et les idées d’inApp, ce qui est gratuit et où sont gardés tes enregistrements.",
    deleteAccount: "Supprimer le compte",
    deleteTitle: "Supprimer ton compte ?",
    deleteBody: "Ton compte sera supprimé avec ses signets, ses notes et son historique de pages. C’est irréversible.",
    deletePurchases: "Les achats liés au compte seront perdus : l’accès Plus payé sur le site ne pourra pas être restauré.",
    deleteAppStore: "Cela n’annule pas un abonnement App Store — il se gère dans les réglages de ton identifiant Apple.",
    deleteConfirmLabel: "Pour confirmer, tape {word}",
    deleteWord: "SUPPRIMER",
    deleteSubmit: "Supprimer définitivement",
    deleteBusy: "Suppression…",
    deleteFailed: "Impossible de supprimer le compte. Réessaie ou écris-nous.",
  },
  ja: {
    description: "inAppのPlus、アカウント、言語、外観。",
    account: "アカウント",
    signInRestore: "ログインしてアクセスを復元",
    signOut: "ログアウト",
    signOutFailed: "ログアウトできませんでした。もう一度お試しください。",
    restoreActive: "このアカウントでPlusが有効です。",
    restoreNone: "このアカウントでは購入が見つかりませんでした。",
    restoreFailed: "アクセスを確認できませんでした。もう一度お試しください。",
    iphoneApp: "iPhoneアプリ",
    paymentOffer: "ウェブ決済の規約",
    storedBrowser: "ブックマークとメモはこのブラウザに保存されます。",
    storedAccount: "ブックマークとメモはあなたのアカウントに保存されます。",
    recordsBrowser:
      "ブックマークとメモはこのブラウザに保存されます。ブックマークを外してもメモは消えません。端末間の同期はありません。",
    recordsAccount:
      "ブックマークとメモはあなたのアカウントに保存され、ログインすればどの端末でも使えます。ブックマークを外してもメモは消えません。",
    aboutDescription: "inAppの分析とアイデアが何からできているか、何が無料か、あなたの記録がどこに保存されるか。",
    deleteAccount: "アカウントを削除",
    deleteTitle: "アカウントを削除しますか？",
    deleteBody: "アカウントは、ブックマーク、メモ、閲覧履歴とともに削除されます。元に戻すことはできません。",
    deletePurchases: "アカウントに紐づく購入は失われます。サイトで支払ったPlusのアクセスは復元できません。",
    deleteAppStore: "App Storeのサブスクリプションはこれでは解約されません。Apple IDの設定で管理してください。",
    deleteConfirmLabel: "確認のため「{word}」と入力してください",
    deleteWord: "削除",
    deleteSubmit: "完全に削除",
    deleteBusy: "削除しています…",
    deleteFailed: "アカウントを削除できませんでした。もう一度試すか、お問い合わせください。",
  },
});
