import { defineStrings } from "../../i18n/strings";

// Web-only strings of «MCP» (/<L>/mcp — the MCP server page, /<L>/mcp/connect — the sign-in
// bridge of the OAuth flow). Client names and their menu paths (Claude Code, Cursor, «Settings →
// MCP»…) stay as the tools show them. `tool_<name>` = one line per server tool (a tool without
// a line shows its English title). No prices here: MCP is part of Plus, the paywall says the rest.
// Word forms: "one|few|many|other". Voice: informal «ты» / du / tu; Japanese です・ます.

export const mcpStrings = defineStrings({
  ru: {
    metaTitle: "MCP-сервер inApp: исследование ниш прямо в редакторе",
    metaDescription:
      "Подключи inApp к Claude Code, Cursor или другому агенту: {niches}, {apps}, {reviews}. На что жалуются пользователи, кто лидирует и за что люди платят.",
    title: "inApp прямо в редакторе",
    subtitle:
      "Подключи inApp к агенту — он будет работать с данными рынка: находить повторяющиеся жалобы, сравнивать приложения и показывать, за что пользователи готовы платить. Каждый вывод можно проверить по исходным отзывам.",
    nichesWord: "ниша|ниши|ниш|ниши",
    appsWord: "приложение|приложения|приложений|приложения",
    reviewsWord: "отзыв|отзыва|отзывов|отзыва",
    reviewsReadWord: "отзыв прочитан|отзыва прочитано|отзывов прочитано|отзыва прочитано",
    toolsWord: "инструмент|инструмента|инструментов|инструмента",
    reviewsGenWord: "отзыва|отзывов|отзывов|отзыва",
    plusTitle: "MCP входит в Plus",
    plusBody:
      "Проверка подключения, каталог ниш и полный разбор демо-ниши «{sample}» — бесплатно. Остальные исследования открываются с Plus, вместе с разборами, идеями, рейтингом и архивом отзывов.",
    plusActive: "Все инструменты сервера открыты.",
    givesTitle: "Что получает агент после подключения",
    give1Title: "Реальные отзывы вместо догадок",
    give1Body: "Размеченные темы каждого приложения и сами исходные отзывы — с фильтрами по теме и оценке.",
    give2Title: "Рейтинг по отзывам",
    give2Body: "Оценка по отзывам и оценка в App Store для каждого приложения: для чего его используют, что хвалят и на что жалуются.",
    give3Title: "Разборы и идеи",
    give3Body: "Тезис ниши, сегменты аудитории, каналы привлечения и идеи со скорингом — всё то же, что на сайте, в контексте твоего кода.",
    exampleTitle: "Главные проблемы в категории «{name}»",
    exampleLead: "Три самые частые темы жалоб в {reviews}:",
    reviewsInWord: "отзыве|отзывах|отзывах|отзыва",
    exampleLink: "Все темы и исходные отзывы",
    installTitle: "Пара минут в любом клиенте",
    pickTool: "Выбери свой инструмент",
    otherClient: "Другой",
    stepPaste: "Вставь команду в терминал",
    stepAddServer: "Добавь сервер",
    stepAddConnector: "Добавь коннектор",
    stepAuth: "Авторизуйся",
    stepAsk: "Спрашивай",
    authorize: "Откроется браузер: войди и нажми «Разрешить».",
    askExample: "Готово. Спроси обычным языком, например: «На что жалуются пользователи трекеров привычек?»",
    cursorAdd: "Одной кнопкой или вручную в файле ~/.cursor/mcp.json:",
    cursorButton: "Добавить в Cursor",
    cursorAuth: "В Settings → MCP у сервера inapp появится Needs login — нажми. {authorize}",
    desktopAdd: "Настройки → Коннекторы → Добавить пользовательский коннектор, вставь адрес:",
    desktopAuth: "Нажми Connect. {authorize}",
    vscodeAdd: "Палитра команд → «MCP: Add Server» → HTTP, вставь адрес:",
    vscodeAuth: "VS Code предложит войти. {authorize}",
    vscodeAsk: "Готово. Спрашивай в Copilot Chat в режиме Agent.",
    otherAdd: "Подойдёт любой клиент с удалёнными MCP по HTTP (streamable). Адрес сервера:",
    otherAuth: "Клиент сам найдёт OAuth. {authorize} Никакие ключи не нужны.",
    freeTier: "Проверка подключения, список ниш и полный разбор одной демо-ниши доступны бесплатно. Остальное откроется с Plus.",
    copy: "Скопировать",
    copied: "Скопировано",
    copyFailed: "Не получилось скопировать — выдели текст вручную.",
    connectionsTitle: "Подключённые клиенты",
    connectionsEmpty: "Пока нет активных подключений. Добавь сервер по инструкции выше — после входа клиент появится здесь.",
    lastActive: "{host} · активность {date}",
    disconnect: "Отключить",
    disconnectFailed: "Не удалось отключить клиента. Попробуй ещё раз.",
    disconnectLabel: "Отключить {client}",
    // Confirmation dialog of «Отключить» (ClarityAccountSection sign-out pattern).
    disconnectConfirm: "Отключить {client}?",
    disconnectConfirmBody: "Агент потеряет доступ к inApp. Подключить его снова можно в любой момент.",
    promptsTitle: "Вопросы, с которых стоит начать",
    prompt1: "На что жалуются пользователи трекеров привычек? Дай реальные цитаты с оценками.",
    prompt2: "Кто лидирует среди сканеров документов и у кого оценка в App Store сильнее всего расходится с отзывами?",
    prompt3: "Сколько люди платят за приложения для сна и за что именно готовы платить?",
    prompt4: "Разбери нишу заметок и предложи, чем новое приложение может отличаться.",
    prompt5: "Спроектируй онбординг так, чтобы он закрывал главную боль ниши трезвости.",
    prompt6: "Откуда приходят пользователи в нишу изучения языков?",
    toolsTitle: "{tools} для исследования ниши",
    toolsNote:
      "Базовая разметка есть у всех {reviews} в {niches}. Для части ниш есть дополнительный слой узких тем конкретных приложений.",
    groupStart: "Старт",
    groupNiche: "Ниша",
    groupApps: "Приложения",
    groupReviews: "Отзывы",
    groupIdeas: "Идеи",
    tool_account_status: "Проверить подключение и доступ аккаунта",
    tool_list_niches: "Все ниши каталога с деньгами и объёмом",
    tool_research_niche: "Быстрый полный разбор ниши в одном вызове",
    tool_get_niche_brief: "Тезис ниши, рынок и сегменты аудитории",
    tool_list_niche_findings: "Выводы разбора с числом наблюдений",
    tool_get_distribution_channels: "Откуда приходят пользователи",
    tool_find_apps: "Найти приложение по названию",
    tool_list_niche_apps: "Конкурентное поле ниши",
    tool_get_app_verdict: "Оценка приложения по отзывам и оценка в App Store",
    tool_get_niche_rating: "Рейтинг ниши целиком",
    tool_list_niche_themes: "Главные жалобы и похвала без заранее известного слова",
    tool_search_themes: "Поиск повторяющихся тем по всем отзывам",
    tool_get_app_themes: "Темы одного приложения с долями",
    tool_get_app_reviews: "Сами тексты отзывов с фильтром по теме и звёздам",
    tool_list_ideas: "Идеи ниши со скорингом",
    tool_get_idea: "Полный разбор идеи: питч, фичи, монетизация",
    faqTitle: "Короткие ответы",
    faq1q: "Что такое MCP?",
    faq1a:
      "Model Context Protocol — открытый стандарт, по которому редакторы и агенты подключают внешние источники данных. Его поддерживают Claude Code, Claude Desktop, Cursor и другие. Ты один раз добавляешь сервер, а агент сам решает, когда к нему обратиться.",
    faq2q: "Нужен ли аккаунт?",
    faq2a:
      "Да. При подключении клиент откроет браузер: войдёшь на сайте и нажмёшь «Разрешить». Проверка подключения, каталог ниш и полный разбор демо-ниши работают бесплатно, остальные исследования — с Plus.",
    faq3q: "Откуда данные?",
    faq3a:
      "Из отзывов App Store, которые мы прочитали и разметили: {reviews} о {apps} в {niches}. Каждое число ведёт к конкретным отзывам — ничего не придумано моделью.",
    faq4q: "С какими клиентами работает?",
    faq4a:
      "Claude Code, Cursor, Claude Desktop, VS Code, Codex и любой другой клиент с удалёнными MCP по HTTP. Вход — через браузер, ключи вставлять не нужно.",
    faq5q: "Сколько стоит?",
    faq5a:
      "MCP входит в inApp Plus вместе с разборами, идеями, рейтингом и архивом отзывов — отдельных тарифов для сервера нет. Условия и цену показывает окно Plus.",
    faq6q: "Данные обновляются?",
    faq6a:
      "Да. Мы дочитываем ниши и добавляем новые, разметка по темам расширяется на весь каталог. Сервер всегда отдаёт текущий срез.",
    aboutAppsWord: "приложении|приложениях|приложениях|приложениях",
    inNichesWord: "нише|нишах|нишах|нишах",
    // /mcp/connect
    connectTitle: "Подключение агента",
    connectBody: "Редактор просит доступ к данным inApp. Войди — и на следующем экране появится кнопка «Разрешить».",
    connectContinue: "Продолжить",
  },
  en: {
    metaTitle: "inApp MCP server: niche research inside your editor",
    metaDescription:
      "Connect inApp to Claude Code, Cursor or any agent: {niches}, {apps}, {reviews}. What users complain about, who leads and what people pay for.",
    title: "inApp inside your editor",
    subtitle:
      "Connect inApp so your agent can work with market data: find recurring complaints, compare apps and show what users are willing to pay for. Every conclusion can be checked against the source reviews.",
    nichesWord: "niche|niches|niches|niches",
    appsWord: "app|apps|apps|apps",
    reviewsWord: "review|reviews|reviews|reviews",
    reviewsReadWord: "review read|reviews read|reviews read|reviews read",
    toolsWord: "tool|tools|tools|tools",
    reviewsGenWord: "review|reviews|reviews|reviews",
    plusTitle: "MCP is part of Plus",
    plusBody:
      "Connection checks, the niche catalog and one complete sample niche, {sample}, are free. The rest of the research opens with Plus, together with the breakdowns, ideas, rating and review archive.",
    plusActive: "Every tool of the server is open to you.",
    givesTitle: "What your agent gets after connecting",
    give1Title: "Real reviews instead of guesses",
    give1Body: "Every app’s labelled themes and the source reviews themselves, filterable by theme and stars.",
    give2Title: "A review-based rating",
    give2Body: "The review score and the App Store rating of every app: what people use it for, what they praise and what they complain about.",
    give3Title: "Breakdowns and ideas",
    give3Body: "The niche thesis, audience segments, acquisition channels and scored ideas — everything the site has, in the context of your code.",
    exampleTitle: "Top problems in {name}",
    exampleLead: "The three most frequent complaint themes across {reviews}:",
    reviewsInWord: "review|reviews|reviews|reviews",
    exampleLink: "Every theme and source review",
    installTitle: "A couple of minutes in any client",
    pickTool: "Pick your AI tool",
    otherClient: "Other",
    stepPaste: "Paste the command into your terminal",
    stepAddServer: "Add the server",
    stepAddConnector: "Add the connector",
    stepAuth: "Authenticate",
    stepAsk: "Ask away",
    authorize: "The browser opens: sign in and tap Allow.",
    askExample: "Done. Ask in plain language, e.g. “What do habit tracker users complain about?”",
    cursorAdd: "One button, or by hand in ~/.cursor/mcp.json:",
    cursorButton: "Add to Cursor",
    cursorAuth: "In Settings → MCP the inapp server shows Needs login: click it. {authorize}",
    desktopAdd: "Settings → Connectors → Add custom connector, paste the URL:",
    desktopAuth: "Hit Connect. {authorize}",
    vscodeAdd: "Command palette → “MCP: Add Server” → HTTP, paste the URL:",
    vscodeAuth: "VS Code offers to sign in. {authorize}",
    vscodeAsk: "Done. Ask in Copilot Chat, Agent mode.",
    otherAdd: "Any client that speaks remote MCP over streamable HTTP. Server URL:",
    otherAuth: "The client discovers OAuth on its own. {authorize} No keys needed.",
    freeTier: "Connection checks, the niche list and one complete sample niche are free. The rest unlocks with Plus.",
    copy: "Copy",
    copied: "Copied",
    copyFailed: "Couldn’t copy — select the text by hand.",
    connectionsTitle: "Connected clients",
    connectionsEmpty: "No active connections yet. Add the server with the steps above; the client appears here after sign-in.",
    lastActive: "{host} · active {date}",
    disconnect: "Disconnect",
    disconnectFailed: "Couldn’t disconnect the client. Try again.",
    disconnectLabel: "Disconnect {client}",
    disconnectConfirm: "Disconnect {client}?",
    disconnectConfirmBody: "The agent will lose access to inApp. You can connect it again at any time.",
    promptsTitle: "Questions to start with",
    prompt1: "What do habit tracker users complain about? Give me real quotes with ratings.",
    prompt2: "Who leads among document scanners, and whose App Store rating diverges most from the reviews?",
    prompt3: "What do people pay for sleep apps, and what exactly are they paying for?",
    prompt4: "Break down the notes niche and suggest how a new app could differ.",
    prompt5: "Design an onboarding that closes the biggest pain in the sobriety niche.",
    prompt6: "Where do users of language learning apps come from?",
    toolsTitle: "{tools} for niche research",
    toolsNote:
      "All {reviews} across {niches} have corpus-level labels. Some niches also have a deeper layer of app-specific themes.",
    groupStart: "Start",
    groupNiche: "Niche",
    groupApps: "Apps",
    groupReviews: "Reviews",
    groupIdeas: "Ideas",
    tool_account_status: "Check the connection and account access",
    tool_list_niches: "Every niche in the catalog, with money and size",
    tool_research_niche: "A quick, complete niche breakdown in one call",
    tool_get_niche_brief: "The niche thesis, market and audience segments",
    tool_list_niche_findings: "Breakdown findings with their observation counts",
    tool_get_distribution_channels: "Where users come from",
    tool_find_apps: "Find an app by name",
    tool_list_niche_apps: "The niche’s competitive field",
    tool_get_app_verdict: "An app’s review score and its App Store rating",
    tool_get_niche_rating: "A niche’s whole rating",
    tool_list_niche_themes: "The loudest complaints and praise, no keyword needed",
    tool_search_themes: "Search recurring themes across all reviews",
    tool_get_app_themes: "One app’s themes with their shares",
    tool_get_app_reviews: "The review texts themselves, filtered by theme and stars",
    tool_list_ideas: "The niche’s ideas with scores",
    tool_get_idea: "A complete idea: pitch, features, monetization",
    faqTitle: "Short answers",
    faq1q: "What is MCP?",
    faq1a:
      "Model Context Protocol, an open standard editors and agents use to plug in external data sources. Claude Code, Claude Desktop, Cursor and others support it. You add the server once and the agent decides when to reach for it.",
    faq2q: "Do I need an account?",
    faq2a:
      "Yes. On connect the client opens the browser: sign in and tap Allow. Connection checks, the niche catalog and one complete sample niche are free; the rest of the research opens with Plus.",
    faq3q: "Where does the data come from?",
    faq3a:
      "From App Store reviews we read and labelled: {reviews} of {apps} in {niches}. Every number traces back to specific reviews; nothing is invented by a model.",
    faq4q: "Which clients work?",
    faq4a:
      "Claude Code, Cursor, Claude Desktop, VS Code, Codex and any other client that speaks remote MCP over HTTP. Sign-in happens in the browser, no keys to paste.",
    faq5q: "What does it cost?",
    faq5a:
      "MCP is part of inApp Plus, together with the breakdowns, ideas, rating and review archive; the server has no separate tiers. The Plus window shows the terms and price.",
    faq6q: "Is the data refreshed?",
    faq6a:
      "Yes. We keep reading more niches and adding new ones, and theme labelling expands across the whole catalog. The server always serves the current cut.",
    aboutAppsWord: "app|apps|apps|apps",
    inNichesWord: "niche|niches|niches|niches",
    connectTitle: "Connecting your agent",
    connectBody: "Your editor is asking for access to inApp data. Sign in, and the next screen shows the Allow button.",
    connectContinue: "Continue",
  },
  de: {
    metaTitle: "inApp-MCP-Server: Nischenrecherche direkt im Editor",
    metaDescription:
      "Verbinde inApp mit Claude Code, Cursor oder einem anderen Agenten: {niches}, {apps}, {reviews}. Worüber sich Nutzer beschweren, wer vorne liegt und wofür Leute zahlen.",
    title: "inApp direkt im Editor",
    subtitle:
      "Verbinde inApp mit deinem Agenten, damit er mit Marktdaten arbeitet: wiederkehrende Beschwerden findet, Apps vergleicht und zeigt, wofür Nutzer zahlen würden. Jedes Ergebnis lässt sich an den Original-Rezensionen prüfen.",
    nichesWord: "Nische|Nischen|Nischen|Nischen",
    appsWord: "App|Apps|Apps|Apps",
    reviewsWord: "Rezension|Rezensionen|Rezensionen|Rezensionen",
    reviewsReadWord: "Rezension gelesen|Rezensionen gelesen|Rezensionen gelesen|Rezensionen gelesen",
    toolsWord: "Werkzeug|Werkzeuge|Werkzeuge|Werkzeuge",
    reviewsGenWord: "Rezension|Rezensionen|Rezensionen|Rezensionen",
    plusTitle: "MCP gehört zu Plus",
    plusBody:
      "Verbindungstest, Nischenkatalog und die komplette Beispielnische {sample} sind kostenlos. Die übrige Recherche öffnet Plus, zusammen mit Analysen, Ideen, Ranking und Rezensionsarchiv.",
    plusActive: "Alle Werkzeuge des Servers stehen dir offen.",
    givesTitle: "Was dein Agent nach dem Verbinden bekommt",
    give1Title: "Echte Rezensionen statt Vermutungen",
    give1Body: "Die gekennzeichneten Themen jeder App und die Original-Rezensionen selbst, filterbar nach Thema und Sternen.",
    give2Title: "Ein Ranking nach Rezensionen",
    give2Body: "Wert aus Rezensionen und App-Store-Bewertung jeder App: wofür sie genutzt wird, was gelobt und was bemängelt wird.",
    give3Title: "Analysen und Ideen",
    give3Body: "These der Nische, Zielgruppensegmente, Akquisekanäle und bewertete Ideen — alles, was die Website hat, im Kontext deines Codes.",
    exampleTitle: "Die größten Probleme in der Kategorie {name}",
    exampleLead: "Die drei häufigsten Beschwerdethemen in {reviews}:",
    reviewsInWord: "Rezension|Rezensionen|Rezensionen|Rezensionen",
    exampleLink: "Alle Themen und Original-Rezensionen",
    installTitle: "Ein paar Minuten in jedem Client",
    pickTool: "Wähl dein KI-Werkzeug",
    otherClient: "Anderer",
    stepPaste: "Füg den Befehl ins Terminal ein",
    stepAddServer: "Füg den Server hinzu",
    stepAddConnector: "Füg den Connector hinzu",
    stepAuth: "Melde dich an",
    stepAsk: "Frag los",
    authorize: "Der Browser öffnet sich: Melde dich an und tipp auf „Allow“.",
    askExample: "Fertig. Frag ganz normal, zum Beispiel: „Worüber beschweren sich Nutzer von Habit-Trackern?“",
    cursorAdd: "Mit einem Klick oder von Hand in ~/.cursor/mcp.json:",
    cursorButton: "Zu Cursor hinzufügen",
    cursorAuth: "In Settings → MCP zeigt der Server inapp „Needs login“ — klick darauf. {authorize}",
    desktopAdd: "Settings → Connectors → Add custom connector, füg die Adresse ein:",
    desktopAuth: "Klick auf Connect. {authorize}",
    vscodeAdd: "Befehlspalette → „MCP: Add Server“ → HTTP, füg die Adresse ein:",
    vscodeAuth: "VS Code bietet die Anmeldung an. {authorize}",
    vscodeAsk: "Fertig. Frag im Copilot Chat im Agent-Modus.",
    otherAdd: "Jeder Client, der Remote-MCP über (streamable) HTTP spricht. Adresse des Servers:",
    otherAuth: "Der Client findet OAuth von selbst. {authorize} Schlüssel brauchst du keine.",
    freeTier: "Verbindungstest, Nischenliste und eine komplette Beispielnische sind kostenlos. Der Rest öffnet sich mit Plus.",
    copy: "Kopieren",
    copied: "Kopiert",
    copyFailed: "Kopieren hat nicht geklappt — markier den Text von Hand.",
    connectionsTitle: "Verbundene Clients",
    connectionsEmpty: "Noch keine aktiven Verbindungen. Füg den Server nach der Anleitung oben hinzu; nach der Anmeldung erscheint der Client hier.",
    lastActive: "{host} · aktiv {date}",
    disconnect: "Trennen",
    disconnectFailed: "Der Client ließ sich nicht trennen. Versuch es noch einmal.",
    disconnectLabel: "{client} trennen",
    disconnectConfirm: "{client} trennen?",
    disconnectConfirmBody: "Der Agent verliert den Zugriff auf inApp. Du kannst ihn jederzeit wieder verbinden.",
    promptsTitle: "Fragen für den Anfang",
    prompt1: "Worüber beschweren sich Nutzer von Habit-Trackern? Gib mir echte Zitate mit Bewertungen.",
    prompt2: "Wer liegt bei Dokumentenscannern vorne, und bei wem weicht die App-Store-Bewertung am stärksten von den Rezensionen ab?",
    prompt3: "Was zahlen Leute für Schlaf-Apps, und wofür genau?",
    prompt4: "Analysier die Nische der Notiz-Apps und schlag vor, wie sich eine neue App abheben kann.",
    prompt5: "Entwirf ein Onboarding, das das größte Problem der Nische Nüchternheit löst.",
    prompt6: "Woher kommen die Nutzer von Sprachlern-Apps?",
    toolsTitle: "{tools} für die Nischenrecherche",
    toolsNote:
      "Alle {reviews} in {niches} haben eine Grundkennzeichnung. Einige Nischen haben zusätzlich eine tiefere Ebene mit App-spezifischen Themen.",
    groupStart: "Start",
    groupNiche: "Nische",
    groupApps: "Apps",
    groupReviews: "Rezensionen",
    groupIdeas: "Ideen",
    tool_account_status: "Verbindung und Kontozugang prüfen",
    tool_list_niches: "Alle Nischen des Katalogs mit Umsatz und Größe",
    tool_research_niche: "Eine schnelle, vollständige Nischenanalyse in einem Aufruf",
    tool_get_niche_brief: "These der Nische, Markt und Zielgruppensegmente",
    tool_list_niche_findings: "Erkenntnisse der Analyse mit der Zahl der Beobachtungen",
    tool_get_distribution_channels: "Woher die Nutzer kommen",
    tool_find_apps: "Eine App nach Namen finden",
    tool_list_niche_apps: "Das Wettbewerbsfeld der Nische",
    tool_get_app_verdict: "Wert einer App aus Rezensionen und ihre App-Store-Bewertung",
    tool_get_niche_rating: "Das ganze Ranking einer Nische",
    tool_list_niche_themes: "Die lautesten Beschwerden und Lobe, ohne Stichwort",
    tool_search_themes: "Wiederkehrende Themen in allen Rezensionen suchen",
    tool_get_app_themes: "Die Themen einer App mit ihren Anteilen",
    tool_get_app_reviews: "Die Rezensionstexte selbst, gefiltert nach Thema und Sternen",
    tool_list_ideas: "Die Ideen der Nische mit Bewertung",
    tool_get_idea: "Eine vollständige Idee: Pitch, Funktionen, Monetarisierung",
    faqTitle: "Kurze Antworten",
    faq1q: "Was ist MCP?",
    faq1a:
      "Model Context Protocol, ein offener Standard, mit dem Editoren und Agenten externe Datenquellen anbinden. Claude Code, Claude Desktop, Cursor und andere unterstützen ihn. Du fügst den Server einmal hinzu, und der Agent entscheidet selbst, wann er ihn nutzt.",
    faq2q: "Brauche ich ein Konto?",
    faq2a:
      "Ja. Beim Verbinden öffnet der Client den Browser: Du meldest dich auf der Website an und tippst auf „Allow“. Verbindungstest, Nischenkatalog und die komplette Beispielnische sind kostenlos, die übrige Recherche gibt es mit Plus.",
    faq3q: "Woher kommen die Daten?",
    faq3a:
      "Aus App-Store-Rezensionen, die wir gelesen und gekennzeichnet haben: {reviews} zu {apps} in {niches}. Jede Zahl führt zu konkreten Rezensionen — nichts davon hat sich ein Modell ausgedacht.",
    faq4q: "Mit welchen Clients funktioniert es?",
    faq4a:
      "Claude Code, Cursor, Claude Desktop, VS Code, Codex und jeder andere Client, der Remote-MCP über HTTP spricht. Die Anmeldung läuft im Browser, Schlüssel musst du keine einfügen.",
    faq5q: "Was kostet das?",
    faq5a:
      "MCP gehört zu inApp Plus, zusammen mit Analysen, Ideen, Ranking und Rezensionsarchiv; eigene Tarife für den Server gibt es nicht. Bedingungen und Preis zeigt das Plus-Fenster.",
    faq6q: "Werden die Daten aktualisiert?",
    faq6a:
      "Ja. Wir lesen weitere Nischen, kommen neue hinzu, und die Kennzeichnung nach Themen wächst auf den ganzen Katalog. Der Server liefert immer den aktuellen Stand.",
    aboutAppsWord: "App|Apps|Apps|Apps",
    inNichesWord: "Nische|Nischen|Nischen|Nischen",
    connectTitle: "Agent verbinden",
    connectBody: "Dein Editor bittet um Zugriff auf die Daten von inApp. Melde dich an, dann erscheint auf dem nächsten Bildschirm der Button „Allow“.",
    connectContinue: "Weiter",
  },
  fr: {
    metaTitle: "Serveur MCP d’inApp : l’étude de niche dans ton éditeur",
    metaDescription:
      "Connecte inApp à Claude Code, Cursor ou un autre agent : {niches}, {apps}, {reviews}. De quoi se plaignent les utilisateurs, qui domine et ce pour quoi les gens paient.",
    title: "inApp dans ton éditeur",
    subtitle:
      "Connecte inApp à ton agent pour qu’il travaille avec des données de marché : repérer les plaintes récurrentes, comparer des applis et montrer ce pour quoi les utilisateurs sont prêts à payer. Chaque conclusion se vérifie dans les avis d’origine.",
    nichesWord: "niche|niches|niches|niches",
    appsWord: "appli|applis|applis|applis",
    reviewsWord: "avis|avis|avis|avis",
    reviewsReadWord: "avis lu|avis lus|avis lus|avis lus",
    toolsWord: "outil|outils|outils|outils",
    reviewsGenWord: "avis|avis|avis|avis",
    plusTitle: "MCP fait partie de Plus",
    plusBody:
      "Le test de connexion, le catalogue des niches et la niche d’exemple complète, {sample}, sont gratuits. Le reste de l’étude s’ouvre avec Plus, avec les décryptages, les idées, le classement et les archives d’avis.",
    plusActive: "Tous les outils du serveur te sont ouverts.",
    givesTitle: "Ce que ton agent obtient une fois connecté",
    give1Title: "De vrais avis plutôt que des suppositions",
    give1Body: "Les thèmes étiquetés de chaque appli et les avis d’origine eux-mêmes, filtrables par thème et par étoiles.",
    give2Title: "Un classement fondé sur les avis",
    give2Body: "La note des avis et la note sur l’App Store de chaque app : à quoi elle sert, ce qui est salué et ce qui est reproché.",
    give3Title: "Décryptages et idées",
    give3Body: "La thèse de la niche, les segments d’audience, les canaux d’acquisition et des idées notées : tout ce qu’a le site, dans le contexte de ton code.",
    exampleTitle: "Les principaux problèmes de la catégorie {name}",
    exampleLead: "Les trois thèmes de plainte les plus fréquents parmi {reviews} :",
    reviewsInWord: "avis|avis|avis|avis",
    exampleLink: "Tous les thèmes et les avis d’origine",
    installTitle: "Quelques minutes dans n’importe quel client",
    pickTool: "Choisis ton outil d’IA",
    otherClient: "Autre",
    stepPaste: "Colle la commande dans ton terminal",
    stepAddServer: "Ajoute le serveur",
    stepAddConnector: "Ajoute le connecteur",
    stepAuth: "Authentifie-toi",
    stepAsk: "Pose tes questions",
    authorize: "Le navigateur s’ouvre : connecte-toi et appuie sur « Allow ».",
    askExample: "C’est prêt. Demande en langage courant, par exemple : « De quoi se plaignent les utilisateurs des applis d’habitudes ? »",
    cursorAdd: "En un clic, ou à la main dans ~/.cursor/mcp.json :",
    cursorButton: "Ajouter à Cursor",
    cursorAuth: "Dans Settings → MCP, le serveur inapp affiche « Needs login » : clique dessus. {authorize}",
    desktopAdd: "Settings → Connectors → Add custom connector, colle l’adresse :",
    desktopAuth: "Clique sur Connect. {authorize}",
    vscodeAdd: "Palette de commandes → « MCP: Add Server » → HTTP, colle l’adresse :",
    vscodeAuth: "VS Code te propose de te connecter. {authorize}",
    vscodeAsk: "C’est prêt. Pose tes questions dans Copilot Chat, en mode Agent.",
    otherAdd: "N’importe quel client qui parle le MCP distant en HTTP (streamable). Adresse du serveur :",
    otherAuth: "Le client trouve OAuth tout seul. {authorize} Aucune clé nécessaire.",
    freeTier: "Le test de connexion, la liste des niches et une niche d’exemple complète sont gratuits. Le reste s’ouvre avec Plus.",
    copy: "Copier",
    copied: "Copié",
    copyFailed: "Impossible de copier : sélectionne le texte à la main.",
    connectionsTitle: "Clients connectés",
    connectionsEmpty: "Aucune connexion active pour l’instant. Ajoute le serveur avec les étapes ci-dessus ; le client apparaîtra ici après la connexion.",
    lastActive: "{host} · actif le {date}",
    disconnect: "Déconnecter",
    disconnectFailed: "Impossible de déconnecter le client. Réessaie.",
    disconnectLabel: "Déconnecter {client}",
    disconnectConfirm: "Déconnecter {client} ?",
    disconnectConfirmBody: "L’agent perdra l’accès à inApp. Tu peux le reconnecter à tout moment.",
    promptsTitle: "Des questions pour commencer",
    prompt1: "De quoi se plaignent les utilisateurs des applis d’habitudes ? Donne-moi de vraies citations avec leur note.",
    prompt2: "Qui domine parmi les scanners de documents, et chez qui la note sur l’App Store s’écarte-t-elle le plus des avis ?",
    prompt3: "Combien les gens paient-ils pour les applis de sommeil, et pour quoi exactement ?",
    prompt4: "Décrypte la niche des applis de notes et propose comment une nouvelle appli pourrait se distinguer.",
    prompt5: "Conçois un onboarding qui règle le principal problème de la niche de la sobriété.",
    prompt6: "D’où viennent les utilisateurs des applis d’apprentissage des langues ?",
    toolsTitle: "{tools} pour étudier une niche",
    toolsNote:
      "Les {reviews} des {niches} ont tous un étiquetage de base. Certaines niches ont en plus une couche plus fine de thèmes propres à chaque appli.",
    groupStart: "Démarrer",
    groupNiche: "Niche",
    groupApps: "Applis",
    groupReviews: "Avis",
    groupIdeas: "Idées",
    tool_account_status: "Vérifier la connexion et l’accès du compte",
    tool_list_niches: "Toutes les niches du catalogue, avec argent et volume",
    tool_research_niche: "Un décryptage complet de la niche en un seul appel",
    tool_get_niche_brief: "La thèse de la niche, le marché et les segments d’audience",
    tool_list_niche_findings: "Les conclusions du décryptage et leur nombre d’observations",
    tool_get_distribution_channels: "D’où viennent les utilisateurs",
    tool_find_apps: "Trouver une appli par son nom",
    tool_list_niche_apps: "Le champ concurrentiel de la niche",
    tool_get_app_verdict: "La note d’une app d’après les avis et sa note sur l’App Store",
    tool_get_niche_rating: "Le classement complet de la niche",
    tool_list_niche_themes: "Les plaintes et les éloges les plus fréquents, sans mot-clé",
    tool_search_themes: "Chercher des thèmes récurrents dans tous les avis",
    tool_get_app_themes: "Les thèmes d’une appli et leur part",
    tool_get_app_reviews: "Les textes des avis eux-mêmes, filtrés par thème et par étoiles",
    tool_list_ideas: "Les idées de la niche, notées",
    tool_get_idea: "Une idée complète : pitch, fonctionnalités, monétisation",
    faqTitle: "Réponses courtes",
    faq1q: "Qu’est-ce que MCP ?",
    faq1a:
      "Model Context Protocol, un standard ouvert grâce auquel éditeurs et agents se branchent sur des sources de données externes. Claude Code, Claude Desktop, Cursor et d’autres le prennent en charge. Tu ajoutes le serveur une fois, et l’agent décide lui-même quand s’en servir.",
    faq2q: "Faut-il un compte ?",
    faq2a:
      "Oui. À la connexion, le client ouvre le navigateur : tu te connectes au site et appuies sur « Allow ». Le test de connexion, le catalogue des niches et la niche d’exemple complète sont gratuits ; le reste de l’étude s’ouvre avec Plus.",
    faq3q: "D’où viennent les données ?",
    faq3a:
      "Des avis de l’App Store que nous avons lus et étiquetés : {reviews} sur {apps} dans {niches}. Chaque chiffre renvoie à des avis précis ; rien n’est inventé par un modèle.",
    faq4q: "Avec quels clients ça marche ?",
    faq4a:
      "Claude Code, Cursor, Claude Desktop, VS Code, Codex et tout autre client qui parle le MCP distant en HTTP. La connexion se fait dans le navigateur, aucune clé à coller.",
    faq5q: "Combien ça coûte ?",
    faq5a:
      "MCP fait partie d’inApp Plus, avec les décryptages, les idées, le classement et les archives d’avis ; le serveur n’a pas de formule à part. La fenêtre Plus indique les conditions et le prix.",
    faq6q: "Les données sont-elles mises à jour ?",
    faq6a:
      "Oui. On continue de lire des niches et d’en ajouter, et l’étiquetage par thèmes s’étend à tout le catalogue. Le serveur fournit toujours l’état actuel.",
    aboutAppsWord: "appli|applis|applis|applis",
    inNichesWord: "niche|niches|niches|niches",
    connectTitle: "Connexion de ton agent",
    connectBody: "Ton éditeur demande l’accès aux données d’inApp. Connecte-toi : l’écran suivant affichera le bouton « Allow ».",
    connectContinue: "Continuer",
  },
  ja: {
    metaTitle: "inAppのMCPサーバー：エディタの中でニッチを調べる",
    metaDescription:
      "inAppをClaude Code、Cursorなどのエージェントにつなげます。{niches}、{apps}、{reviews}。利用者の不満、トップのアプリ、人々がお金を払う理由がわかります。",
    title: "エディタの中のinApp",
    subtitle:
      "inAppをエージェントにつなぐと、市場データで作業できます。繰り返し出る不満を見つけ、アプリを比べ、利用者が何にお金を払うのかを示します。どの結論も元のレビューで確かめられます。",
    nichesWord: "ニッチ",
    appsWord: "アプリ",
    reviewsWord: "件のレビュー",
    reviewsReadWord: "件のレビューを読了",
    toolsWord: "ツール",
    reviewsGenWord: "件のレビュー",
    plusTitle: "MCPはPlusに含まれます",
    plusBody:
      "接続の確認、ニッチのカタログ、サンプルのニッチ「{sample}」の分析全体は無料です。ほかの調査は、分析、アイデア、ランキング、レビューのアーカイブとあわせてPlusで開きます。",
    plusActive: "サーバーのすべてのツールを使えます。",
    givesTitle: "接続するとエージェントが得られるもの",
    give1Title: "推測ではなく実際のレビュー",
    give1Body: "各アプリのラベル付きテーマと元のレビューそのもの。テーマと星で絞り込めます。",
    give2Title: "レビューにもとづくランキング",
    give2Body: "各アプリのレビュースコアとApp Storeの評価。使われ方、評価されている点と不満点がわかります。",
    give3Title: "分析とアイデア",
    give3Body: "ニッチの要点、利用者のセグメント、集客チャネル、スコアつきのアイデア。サイトにあるものすべてを、コードの文脈で使えます。",
    exampleTitle: "{name}カテゴリの主な問題",
    exampleLead: "{reviews}で最も多い不満のテーマ3つ：",
    reviewsInWord: "件のレビュー",
    exampleLink: "すべてのテーマと元のレビュー",
    installTitle: "どのクライアントでも数分で完了",
    pickTool: "使っているAIツールを選んでください",
    otherClient: "その他",
    stepPaste: "コマンドをターミナルに貼り付けます",
    stepAddServer: "サーバーを追加します",
    stepAddConnector: "コネクタを追加します",
    stepAuth: "認証します",
    stepAsk: "質問します",
    authorize: "ブラウザが開くので、ログインして「Allow」を押します。",
    askExample: "完了です。たとえば「習慣トラッカーの利用者は何に不満を持っていますか？」のように普通の言葉で質問してください。",
    cursorAdd: "ボタンひとつで、または~/.cursor/mcp.jsonに手動で：",
    cursorButton: "Cursorに追加",
    cursorAuth: "Settings → MCPでinappサーバーに「Needs login」が表示されたら押します。{authorize}",
    desktopAdd: "Settings → Connectors → Add custom connectorを開き、アドレスを貼り付けます：",
    desktopAuth: "Connectを押します。{authorize}",
    vscodeAdd: "コマンドパレット → 「MCP: Add Server」 → HTTPを選び、アドレスを貼り付けます：",
    vscodeAuth: "VS Codeがログインを提案します。{authorize}",
    vscodeAsk: "完了です。Copilot ChatのAgentモードで質問してください。",
    otherAdd: "HTTP（streamable）でリモートMCPを使えるクライアントならどれでも使えます。サーバーのアドレス：",
    otherAuth: "クライアントがOAuthを自動で見つけます。{authorize}キーは不要です。",
    freeTier: "接続の確認、ニッチの一覧、サンプルのニッチ1つの分析全体は無料です。ほかはPlusで開きます。",
    copy: "コピー",
    copied: "コピーしました",
    copyFailed: "コピーできませんでした。テキストを手動で選択してください。",
    connectionsTitle: "接続中のクライアント",
    connectionsEmpty: "有効な接続はまだありません。上の手順でサーバーを追加すると、ログイン後にクライアントがここに表示されます。",
    lastActive: "{host}・最終利用{date}",
    disconnect: "切断",
    disconnectFailed: "クライアントを切断できませんでした。もう一度お試しください。",
    disconnectLabel: "{client}を切断",
    disconnectConfirm: "{client}の接続を解除しますか？",
    disconnectConfirmBody: "エージェントはinAppにアクセスできなくなります。いつでも再接続できます。",
    promptsTitle: "最初におすすめの質問",
    prompt1: "習慣トラッカーの利用者は何に不満を持っていますか？評価つきで実際の引用を見せてください。",
    prompt2: "文書スキャナーで上位のアプリはどれですか？App Storeの評価がレビューと最もずれているのはどのアプリですか？",
    prompt3: "睡眠アプリに人々はいくら払っていて、具体的に何にお金を払っていますか？",
    prompt4: "メモアプリのニッチを分析して、新しいアプリがどう差別化できるか提案してください。",
    prompt5: "禁酒アプリのニッチで最大の悩みを解決するオンボーディングを設計してください。",
    prompt6: "語学学習アプリの利用者はどこから来ていますか？",
    toolsTitle: "ニッチ調査のための{tools}",
    toolsNote:
      "{niches}の{reviews}すべてに基本のラベルがあります。一部のニッチには、アプリごとの細かいテーマの層もあります。",
    groupStart: "スタート",
    groupNiche: "ニッチ",
    groupApps: "アプリ",
    groupReviews: "レビュー",
    groupIdeas: "アイデア",
    tool_account_status: "接続とアカウントのアクセスを確認",
    tool_list_niches: "カタログの全ニッチ（売上と規模つき）",
    tool_research_niche: "1回の呼び出しでニッチを丸ごと分析",
    tool_get_niche_brief: "ニッチの要点、市場、利用者のセグメント",
    tool_list_niche_findings: "観察数つきの分析結果",
    tool_get_distribution_channels: "利用者がどこから来るか",
    tool_find_apps: "名前でアプリを探す",
    tool_list_niche_apps: "ニッチの競合状況",
    tool_get_app_verdict: "アプリのレビュースコアとApp Storeの評価",
    tool_get_niche_rating: "ニッチのランキング全体",
    tool_list_niche_themes: "キーワードなしで分かる主な不満と称賛",
    tool_search_themes: "すべてのレビューから繰り返し出るテーマを検索",
    tool_get_app_themes: "1つのアプリのテーマと割合",
    tool_get_app_reviews: "テーマと星で絞り込めるレビュー本文",
    tool_list_ideas: "スコアつきのニッチのアイデア",
    tool_get_idea: "アイデアの全体像：ピッチ、機能、収益化",
    faqTitle: "よくある質問",
    faq1q: "MCPとは何ですか？",
    faq1a:
      "Model Context Protocolは、エディタやエージェントが外部のデータソースにつながるためのオープンな標準です。Claude Code、Claude Desktop、Cursorなどが対応しています。サーバーを一度追加すれば、いつ使うかはエージェントが自分で判断します。",
    faq2q: "アカウントは必要ですか？",
    faq2a:
      "はい。接続するとクライアントがブラウザを開くので、サイトにログインして「Allow」を押します。接続の確認、ニッチのカタログ、サンプルのニッチの分析全体は無料で、ほかの調査はPlusで使えます。",
    faq3q: "データはどこから来ていますか？",
    faq3a:
      "私たちが読んでラベルを付けたApp Storeのレビューです。{niches}の{apps}についての{reviews}があります。どの数字も具体的なレビューにたどれます。モデルが作り出したものはありません。",
    faq4q: "どのクライアントで使えますか？",
    faq4a:
      "Claude Code、Cursor、Claude Desktop、VS Code、Codex、そしてHTTPでリモートMCPを使えるほかのクライアントです。ログインはブラウザで行い、キーを貼り付ける必要はありません。",
    faq5q: "料金はいくらですか？",
    faq5a:
      "MCPは分析、アイデア、ランキング、レビューのアーカイブとあわせてinApp Plusに含まれます。サーバー専用のプランはありません。条件と価格はPlusの画面に表示されます。",
    faq6q: "データは更新されますか？",
    faq6a:
      "はい。ニッチを読み進めて新しいニッチを追加し、テーマのラベル付けをカタログ全体に広げています。サーバーは常に最新の状態を返します。",
    aboutAppsWord: "アプリ",
    inNichesWord: "ニッチ",
    connectTitle: "エージェントの接続",
    connectBody: "エディタがinAppのデータへのアクセスを求めています。ログインすると、次の画面に「Allow」ボタンが表示されます。",
    connectContinue: "続ける",
  },
});

export type McpStrings = (typeof mcpStrings)["ru"];
