import { defineStrings } from "../../i18n/strings";

// Web-only strings of the «Разборы» side (catalog, topic pages): the site-only blocks the app
// does not have (apps in the topic, links to the previous site, App Store promo) and the list
// of topics not rewritten yet (DECISIONS §3–§4). App UI strings come from content/v2/<L>/ui.json.
// Voice: informal «ты» / du / tu; Japanese です・ます like ui.ja.json.
// de/fr/ja visitors are sent to the English archive for old pages, hence `englishNote`.

export const researchStrings = defineStrings({
  ru: {
    soonTitle: "Скоро в новом формате",
    soonBody: "Эти разборы пока открываются в прежней версии сайта. Скоро перепишем их, как остальные.",
    appsTitle: "Приложения в этой теме",
    appsLead: "Самые оценённые приложения в выдаче App Store по запросу «{term}».",
    appsSource: "App Store · {region} · {date}",
    appsListLabel: "Приложения по числу оценок",
    appsShowMore: "Показать ещё {n}",
    appStoreLink: "{name} в App Store (откроется в новой вкладке)",
    appPage: "Страница приложения",
    appPageLabel: "Страница приложения {name}",
    appReviews: "Отзывы",
    appReviewsLabel: "Отзывы о приложении {name}",
    allReviews: "Все отзывы по теме",
    oldVersion: "Прежняя версия разбора",
    englishNote: "",
    ratingLabel: "Рейтинг {rating} из 5",
    noRating: "нет оценок",
    ratingsOne: "оценка",
    ratingsFew: "оценки",
    ratingsMany: "оценок",
    ratingsOther: "оценки",
    promoTitle: "Разборы и идеи — в приложении inApp",
    promoBody: "Читай на iPhone: закладки и заметки всегда под рукой.",
  },
  en: {
    soonTitle: "Coming soon in the new format",
    soonBody: "These breakdowns still open in the previous version of the site. We’ll rewrite them soon, like the rest.",
    appsTitle: "Apps in this category",
    appsLead: "The most-rated apps in App Store results for “{term}”.",
    appsSource: "App Store · {region} · {date}",
    appsListLabel: "Apps by number of ratings",
    appsShowMore: "Show {n} more",
    appStoreLink: "{name} on the App Store (opens in a new tab)",
    appPage: "App page",
    appPageLabel: "{name}: app page",
    appReviews: "Reviews",
    appReviewsLabel: "Reviews of {name}",
    allReviews: "All reviews in this category",
    oldVersion: "Previous version of this breakdown",
    englishNote: "",
    ratingLabel: "Rated {rating} out of 5",
    noRating: "no ratings",
    ratingsOne: "rating",
    ratingsFew: "ratings",
    ratingsMany: "ratings",
    ratingsOther: "ratings",
    promoTitle: "Breakdowns and ideas in the inApp app",
    promoBody: "Read on your iPhone, with bookmarks and notes always at hand.",
  },
  de: {
    soonTitle: "Bald im neuen Format",
    soonBody:
      "Diese Analysen öffnen sich vorerst in der bisherigen Version der Website, auf Englisch. Bald schreiben wir sie wie die anderen neu.",
    appsTitle: "Apps in dieser Kategorie",
    appsLead: "Die am häufigsten bewerteten Apps in den App-Store-Ergebnissen für „{term}“.",
    appsSource: "App Store · {region} · {date}",
    appsListLabel: "Apps nach Anzahl der Bewertungen",
    appsShowMore: "{n} weitere anzeigen",
    appStoreLink: "{name} im App Store (öffnet sich in einem neuen Tab)",
    appPage: "App-Seite",
    appPageLabel: "{name}: App-Seite",
    appReviews: "Rezensionen",
    appReviewsLabel: "Rezensionen zu {name}",
    allReviews: "Alle Rezensionen zu dieser Kategorie",
    oldVersion: "Bisherige Version dieser Analyse",
    englishNote: "(auf Englisch)",
    ratingLabel: "Bewertung {rating} von 5",
    noRating: "keine Bewertungen",
    ratingsOne: "Bewertung",
    ratingsFew: "Bewertungen",
    ratingsMany: "Bewertungen",
    ratingsOther: "Bewertungen",
    promoTitle: "Analysen und Ideen in der inApp-App",
    promoBody: "Lies auf dem iPhone – Lesezeichen und Notizen hast du immer dabei.",
  },
  fr: {
    soonTitle: "Bientôt au nouveau format",
    soonBody:
      "Ces décryptages s’ouvrent encore dans l’ancienne version du site, en anglais. On les réécrit bientôt, comme les autres.",
    appsTitle: "Les apps de cette catégorie",
    appsLead: "Les apps les plus notées dans les résultats de l’App Store pour « {term} ».",
    appsSource: "App Store · {region} · {date}",
    appsListLabel: "Apps par nombre de notes",
    appsShowMore: "Afficher {n} de plus",
    appStoreLink: "{name} sur l’App Store (s’ouvre dans un nouvel onglet)",
    appPage: "Page de l’app",
    appPageLabel: "{name} : page de l’app",
    appReviews: "Avis",
    appReviewsLabel: "Avis sur {name}",
    allReviews: "Tous les avis de cette catégorie",
    oldVersion: "Ancienne version de ce décryptage",
    englishNote: "(en anglais)",
    ratingLabel: "Note de {rating} sur 5",
    noRating: "aucune note",
    ratingsOne: "note",
    ratingsFew: "notes",
    ratingsMany: "notes",
    ratingsOther: "notes",
    promoTitle: "Décryptages et idées dans l’app inApp",
    promoBody: "Lis sur ton iPhone, avec tes signets et tes notes toujours à portée de main.",
  },
  ja: {
    soonTitle: "まもなく新しい形式で",
    soonBody: "これらの分析は、今のところ以前のサイト（英語）で開きます。ほかの分析と同じように、近いうちに書き直します。",
    appsTitle: "このカテゴリーのアプリ",
    appsLead: "App Storeで「{term}」と検索したときの、評価数の多いアプリです。",
    appsSource: "App Store · {region} · {date}",
    appsListLabel: "評価数順のアプリ",
    appsShowMore: "さらに{n}件を表示",
    appStoreLink: "App Storeの{name}（新しいタブで開きます）",
    appPage: "アプリのページ",
    appPageLabel: "{name}のページ",
    appReviews: "レビュー",
    appReviewsLabel: "{name}のレビュー",
    allReviews: "このカテゴリーのレビューをすべて見る",
    oldVersion: "この分析の以前の版",
    englishNote: "（英語）",
    ratingLabel: "5点中{rating}点",
    noRating: "評価なし",
    ratingsOne: "件の評価",
    ratingsFew: "件の評価",
    ratingsMany: "件の評価",
    ratingsOther: "件の評価",
    promoTitle: "分析とアイデアをinAppアプリで",
    promoBody: "iPhoneで読めます。ブックマークとメモもいつでも手元に。",
  },
});

export type ResearchStrings = (typeof researchStrings)["ru"];
