import { defineStrings } from "@/site/i18n/strings";

// Web strings of «Пульс» (SPEC: app_04_inapp/Documentation/PulseDemand-2026-09-24/SPEC.md).
// Need titles and summaries come from content/v2/pulse-demand.json per locale; this table holds
// the interface only. Plural forms: *One / *Few / *Many follow pluralCategory() of
// src/site/i18n/translate.ts (en/de/fr: few = many = "other"; ja has one form).
// No «Просят / Жалуются» anywhere (owner, 2026-09-25: «убрать просят жалуются это мусор»): the
// need's kind stays in the data and is never shown. The word levels (level*) follow painLevel()
// in ./gauge.ts, the one place with the thresholds.
export const pulseStrings = defineStrings({
  ru: {
    title: "Пульс",
    subtitle: "Конкретные боли из отзывов о приложениях — и насколько они сильные",
    metaDescription: "Конкретные боли из отзывов App Store по категориям приложений: сколько людей об этом пишут и насколько это больно.",
    painAria: "Боль {score} из 10, {level}.",
    painOf: "боль {score} из 10",
    levelMild: "Фоновая",
    levelNoticeable: "Заметная",
    levelStrong: "Сильная",
    levelAcute: "Острая",
    countsAria: "{reviews}, {apps}.",
    category: "Категория",
    allCategories: "Все категории",
    search: "Поиск",
    searchPlaceholder: "Например, виджет или синхронизация",
    searchSubmit: "Найти",
    apply: "Показать",
    reset: "Сбросить",
    reviewsOne: "{n} отзыв",
    reviewsFew: "{n} отзыва",
    reviewsMany: "{n} отзывов",
    appsOne: "{n} приложение",
    appsFew: "{n} приложения",
    appsMany: "{n} приложений",
    inAppsOne: "в {n} из {total} приложения",
    inAppsFew: "в {n} из {total} приложений",
    inAppsMany: "в {n} из {total} приложений",
    aboutAppsOne: "{reviews} о {n} приложении",
    aboutAppsFew: "{reviews} о {n} приложениях",
    aboutAppsMany: "{reviews} о {n} приложениях",
    shareOfCategory: "{share} отзывов категории",
    verified: "проверено вручную: {correct} из {sample}",
    breakdownTitle: "Из чего складывается {score}/10",
    partShare: "Доля отзывов категории",
    partApps: "Приложения",
    partReviews: "Отзывы",
    partPoints: "{value} из {max}",
    appsOf: "{n} из {total}",
    breakdownTotal: "Итого",
    whereTitle: "Где об этом пишут",
    dotsNote: "Каждая точка — одно приложение категории",
    dotsWith: "{n} с этой болью",
    dotsWithout: "{n} без",
    ratingsTitle: "Оценки в этих отзывах",
    ratingAria: "{stars} из 5: {count}",
    rating: "Оценка {rating} из 5",
    topAppsTitle: "Чаще всего пишут в",
    evidenceTitle: "Что пишут",
    original: "Показать оригинал",
    lockedTitle: "Остальные цитаты — в Plus",
    lockedBody: "Они открываются вместе с разбором категории: с Plus или доступом к этой категории.",
    signIn: "Уже есть доступ? Войти",
    research: "Разбор категории",
    moreInCategory: "Ещё в категории",
    embedTitle: "Пульс категории",
    topPain: "Главная боль",
    needsOne: "{n} потребность",
    needsFew: "{n} потребности",
    needsMany: "{n} потребностей",
    allNeedsOne: "Все {n} потребность",
    allNeedsFew: "Все {n} потребности",
    allNeedsMany: "Все {n} потребностей",
    about: "Как считаем",
    aboutSample: "Выборка — до 500 последних отзывов у ~100 популярных приложений каждой категории в App Store. Каждую потребность ищем по всем отзывам категории, а совпадения выборочно проверяем вручную: точность не ниже 80%.",
    aboutScore: "«Боль» — условная оценка от 1 до 10: наполовину она зависит от доли отзывов категории, где об этом пишут, на 30% — от того, сколько таких отзывов всего, на 20% — от доли приложений, где это встречается. Это не поисковый спрос и не размер рынка.",
    aboutLevels: "Словами: {scale}.",
    empty: "Пульс ещё собирается",
    emptyBody: "Скоро здесь появятся конкретные боли из отзывов.",
    noResults: "Ничего не нашли",
    noResultsBody: "Попробуй другую категорию или более короткий запрос.",
    pages: "Страницы",
    next: "Дальше",
    previous: "Назад",
  },
  en: {
    title: "Pulse",
    subtitle: "Concrete pains from app reviews — and how strong they are",
    metaDescription: "Concrete pains from App Store reviews, by app category: how many people write about each one and how much it hurts.",
    painAria: "Pain {score} out of 10, {level}.",
    painOf: "pain {score} of 10",
    levelMild: "Mild",
    levelNoticeable: "Noticeable",
    levelStrong: "Strong",
    levelAcute: "Acute",
    countsAria: "{reviews}, {apps}.",
    category: "Category",
    allCategories: "All categories",
    search: "Search",
    searchPlaceholder: "For example, widget or sync",
    searchSubmit: "Search",
    apply: "Show",
    reset: "Reset",
    reviewsOne: "{n} review",
    reviewsFew: "{n} reviews",
    reviewsMany: "{n} reviews",
    appsOne: "{n} app",
    appsFew: "{n} apps",
    appsMany: "{n} apps",
    inAppsOne: "in {n} of {total} app",
    inAppsFew: "in {n} of {total} apps",
    inAppsMany: "in {n} of {total} apps",
    aboutAppsOne: "{reviews} of {n} app",
    aboutAppsFew: "{reviews} of {n} apps",
    aboutAppsMany: "{reviews} of {n} apps",
    shareOfCategory: "{share} of the category’s reviews",
    verified: "hand-checked: {correct} of {sample}",
    breakdownTitle: "How the {score}/10 adds up",
    partShare: "Share of the category’s reviews",
    partApps: "Apps",
    partReviews: "Reviews",
    partPoints: "{value} of {max}",
    appsOf: "{n} of {total}",
    breakdownTotal: "Total",
    whereTitle: "Where people write about it",
    dotsNote: "Each dot is one app in the category",
    dotsWith: "{n} with this pain",
    dotsWithout: "{n} without",
    ratingsTitle: "Ratings in these reviews",
    ratingAria: "{stars} out of 5: {count}",
    rating: "Rated {rating} out of 5",
    topAppsTitle: "Most often in",
    evidenceTitle: "What people write",
    original: "Show original",
    lockedTitle: "More quotes with Plus",
    lockedBody: "They open together with the category breakdown: with Plus or access to this category.",
    signIn: "Already have access? Sign in",
    research: "Category breakdown",
    moreInCategory: "More in this category",
    embedTitle: "Category pulse",
    topPain: "Top pain",
    needsOne: "{n} need",
    needsFew: "{n} needs",
    needsMany: "{n} needs",
    allNeedsOne: "{n} need",
    allNeedsFew: "All {n} needs",
    allNeedsMany: "All {n} needs",
    about: "How we count",
    aboutSample: "The sample is up to 500 recent App Store reviews for each of about 100 popular apps per category. We look for each need across all of the category’s reviews and check a random sample of matches by hand: at least 80% are correct.",
    aboutScore: "“Pain” is a rough score from 1 to 10: half comes from the share of the category’s reviews that mention it, 30% from how many such reviews there are in total, 20% from the share of apps where it comes up. It is not search demand and not market size.",
    aboutLevels: "In words: {scale}.",
    empty: "Pulse is still being gathered",
    emptyBody: "Concrete pains from reviews will appear here soon.",
    noResults: "Nothing found",
    noResultsBody: "Try another category or a shorter query.",
    pages: "Pages",
    next: "Next",
    previous: "Previous",
  },
  de: {
    title: "Puls",
    subtitle: "Konkrete Schmerzpunkte aus App-Bewertungen — und wie stark sie sind",
    metaDescription: "Konkrete Schmerzpunkte aus App-Store-Bewertungen, nach App-Kategorien: wie viele Menschen darüber schreiben und wie sehr es schmerzt.",
    painAria: "Schmerz {score} von 10, {level}.",
    painOf: "Schmerz {score} von 10",
    levelMild: "Leicht",
    levelNoticeable: "Spürbar",
    levelStrong: "Stark",
    levelAcute: "Akut",
    countsAria: "{reviews}, {apps}.",
    category: "Kategorie",
    allCategories: "Alle Kategorien",
    search: "Suche",
    searchPlaceholder: "Zum Beispiel Widget oder Synchronisierung",
    searchSubmit: "Suchen",
    apply: "Anzeigen",
    reset: "Zurücksetzen",
    reviewsOne: "{n} Bewertung",
    reviewsFew: "{n} Bewertungen",
    reviewsMany: "{n} Bewertungen",
    appsOne: "{n} App",
    appsFew: "{n} Apps",
    appsMany: "{n} Apps",
    inAppsOne: "in {n} von {total} App",
    inAppsFew: "in {n} von {total} Apps",
    inAppsMany: "in {n} von {total} Apps",
    aboutAppsOne: "{reviews} zu {n} App",
    aboutAppsFew: "{reviews} zu {n} Apps",
    aboutAppsMany: "{reviews} zu {n} Apps",
    shareOfCategory: "{share} der Bewertungen der Kategorie",
    verified: "von Hand geprüft: {correct} von {sample}",
    breakdownTitle: "Woraus sich {score}/10 zusammensetzt",
    partShare: "Anteil an den Bewertungen der Kategorie",
    partApps: "Apps",
    partReviews: "Bewertungen",
    partPoints: "{value} von {max}",
    appsOf: "{n} von {total}",
    breakdownTotal: "Summe",
    whereTitle: "Wo darüber geschrieben wird",
    dotsNote: "Jeder Punkt ist eine App der Kategorie",
    dotsWith: "{n} mit diesem Schmerz",
    dotsWithout: "{n} ohne",
    ratingsTitle: "Sterne in diesen Bewertungen",
    ratingAria: "{stars} von 5: {count}",
    rating: "{rating} von 5 Sternen",
    topAppsTitle: "Am häufigsten bei",
    evidenceTitle: "Was Menschen schreiben",
    original: "Original anzeigen",
    lockedTitle: "Weitere Zitate mit Plus",
    lockedBody: "Sie werden zusammen mit der Analyse der Kategorie freigeschaltet: mit Plus oder Zugang zu dieser Kategorie.",
    signIn: "Schon Zugang? Anmelden",
    research: "Analyse der Kategorie",
    moreInCategory: "Mehr in dieser Kategorie",
    embedTitle: "Puls der Kategorie",
    topPain: "Größter Schmerz",
    needsOne: "{n} Bedürfnis",
    needsFew: "{n} Bedürfnisse",
    needsMany: "{n} Bedürfnisse",
    allNeedsOne: "{n} Bedürfnis",
    allNeedsFew: "Alle {n} Bedürfnisse",
    allNeedsMany: "Alle {n} Bedürfnisse",
    about: "So zählen wir",
    aboutSample: "Die Stichprobe umfasst bis zu 500 aktuelle App-Store-Bewertungen von jeweils rund 100 beliebten Apps pro Kategorie. Jedes Bedürfnis suchen wir in allen Bewertungen der Kategorie und prüfen eine Zufallsauswahl der Treffer von Hand: Mindestens 80 % sind korrekt.",
    aboutScore: "„Schmerz“ ist ein grober Wert von 1 bis 10: zur Hälfte der Anteil der Bewertungen der Kategorie, die es erwähnen, zu 30 % die Gesamtzahl solcher Bewertungen, zu 20 % der Anteil der Apps, in denen es vorkommt. Das ist weder Suchnachfrage noch Marktgröße.",
    aboutLevels: "In Worten: {scale}.",
    empty: "Der Puls wird noch gesammelt",
    emptyBody: "Hier erscheinen bald konkrete Schmerzpunkte aus Bewertungen.",
    noResults: "Nichts gefunden",
    noResultsBody: "Versuch eine andere Kategorie oder eine kürzere Suche.",
    pages: "Seiten",
    next: "Weiter",
    previous: "Zurück",
  },
  fr: {
    title: "Pouls",
    subtitle: "Les douleurs concrètes tirées des avis d’apps — et leur intensité",
    metaDescription: "Douleurs concrètes tirées des avis de l’App Store, par catégorie d’apps : combien de personnes en parlent et à quel point ça fait mal.",
    painAria: "Douleur {score} sur 10, {level}.",
    painOf: "douleur {score} sur 10",
    levelMild: "Légère",
    levelNoticeable: "Notable",
    levelStrong: "Forte",
    levelAcute: "Aiguë",
    countsAria: "{reviews}, {apps}.",
    category: "Catégorie",
    allCategories: "Toutes les catégories",
    search: "Recherche",
    searchPlaceholder: "Par exemple, widget ou synchronisation",
    searchSubmit: "Rechercher",
    apply: "Afficher",
    reset: "Réinitialiser",
    reviewsOne: "{n} avis",
    reviewsFew: "{n} avis",
    reviewsMany: "{n} avis",
    appsOne: "{n} appli",
    appsFew: "{n} applis",
    appsMany: "{n} applis",
    inAppsOne: "dans {n} appli sur {total}",
    inAppsFew: "dans {n} applis sur {total}",
    inAppsMany: "dans {n} applis sur {total}",
    aboutAppsOne: "{reviews} sur {n} appli",
    aboutAppsFew: "{reviews} sur {n} applis",
    aboutAppsMany: "{reviews} sur {n} applis",
    shareOfCategory: "{share} des avis de la catégorie",
    verified: "vérifié à la main : {correct} sur {sample}",
    breakdownTitle: "D’où vient ce {score}/10",
    partShare: "Part des avis de la catégorie",
    partApps: "Applis",
    partReviews: "Avis",
    partPoints: "{value} sur {max}",
    appsOf: "{n} sur {total}",
    breakdownTotal: "Total",
    whereTitle: "Où on en parle",
    dotsNote: "Chaque point est une appli de la catégorie",
    dotsWith: "{n} avec cette douleur",
    dotsWithout: "{n} sans",
    ratingsTitle: "Notes dans ces avis",
    ratingAria: "{stars} sur 5 : {count}",
    rating: "Note : {rating} sur 5",
    topAppsTitle: "Le plus souvent dans",
    evidenceTitle: "Ce que les gens écrivent",
    original: "Voir l’original",
    lockedTitle: "Plus de citations avec Plus",
    lockedBody: "Elles s’ouvrent avec l’analyse de la catégorie : avec Plus ou un accès à cette catégorie.",
    signIn: "Déjà un accès ? Se connecter",
    research: "Analyse de la catégorie",
    moreInCategory: "Aussi dans cette catégorie",
    embedTitle: "Pouls de la catégorie",
    topPain: "Douleur principale",
    needsOne: "{n} besoin",
    needsFew: "{n} besoins",
    needsMany: "{n} besoins",
    allNeedsOne: "{n} besoin",
    allNeedsFew: "Voir les {n} besoins",
    allNeedsMany: "Voir les {n} besoins",
    about: "Comment on compte",
    aboutSample: "L’échantillon compte jusqu’à 500 avis récents de l’App Store pour environ 100 apps populaires par catégorie. Nous cherchons chaque besoin dans tous les avis de la catégorie et vérifions à la main un échantillon des correspondances : au moins 80 % sont justes.",
    aboutScore: "La « douleur » est une note indicative de 1 à 10 : la moitié vient de la part des avis de la catégorie qui en parlent, 30 % du nombre total de ces avis, 20 % de la part des apps où cela revient. Ce n’est ni la demande de recherche ni la taille du marché.",
    aboutLevels: "En mots : {scale}.",
    empty: "Le pouls est encore en cours de collecte",
    emptyBody: "Des douleurs concrètes tirées des avis apparaîtront bientôt ici.",
    noResults: "Aucun résultat",
    noResultsBody: "Essaie une autre catégorie ou une recherche plus courte.",
    pages: "Pages",
    next: "Suivant",
    previous: "Précédent",
  },
  ja: {
    title: "パルス",
    subtitle: "アプリのレビューから見える具体的なペイン — そしてその強さ",
    metaDescription: "App Storeのレビューから、アプリのカテゴリごとに具体的なペインをまとめました。どれくらいの人が書いているか、どれほど痛いかがわかります。",
    painAria: "ペイン 10段階中{score}、{level}。",
    painOf: "ペイン {score}/10",
    levelMild: "軽い",
    levelNoticeable: "目立つ",
    levelStrong: "強い",
    levelAcute: "深刻",
    countsAria: "{reviews}、{apps}。",
    category: "カテゴリ",
    allCategories: "すべてのカテゴリ",
    search: "検索",
    searchPlaceholder: "例：ウィジェット、同期",
    searchSubmit: "検索",
    apply: "表示",
    reset: "リセット",
    reviewsOne: "{n}件のレビュー",
    reviewsFew: "{n}件のレビュー",
    reviewsMany: "{n}件のレビュー",
    appsOne: "{n}アプリ",
    appsFew: "{n}アプリ",
    appsMany: "{n}アプリ",
    inAppsOne: "{total}アプリ中{n}アプリ",
    inAppsFew: "{total}アプリ中{n}アプリ",
    inAppsMany: "{total}アプリ中{n}アプリ",
    aboutAppsOne: "{n}アプリの{reviews}",
    aboutAppsFew: "{n}アプリの{reviews}",
    aboutAppsMany: "{n}アプリの{reviews}",
    shareOfCategory: "カテゴリのレビューの{share}",
    verified: "手作業で確認：{sample}件中{correct}件が正確",
    breakdownTitle: "{score}/10 の内訳",
    partShare: "カテゴリのレビューに占める割合",
    partApps: "アプリ",
    partReviews: "レビュー数",
    partPoints: "{value} / {max}",
    appsOf: "{total}中{n}",
    breakdownTotal: "合計",
    whereTitle: "どのアプリで書かれているか",
    dotsNote: "点1つがカテゴリのアプリ1つです",
    dotsWith: "あり {n}",
    dotsWithout: "なし {n}",
    ratingsTitle: "これらのレビューの評価",
    ratingAria: "星{stars}：{count}件",
    rating: "評価 {rating}/5",
    topAppsTitle: "よく書かれているアプリ",
    evidenceTitle: "レビューの声",
    original: "原文を表示",
    lockedTitle: "残りの引用はPlusで",
    lockedBody: "カテゴリの分析と一緒に開放されます。Plus またはこのカテゴリへのアクセスが必要です。",
    signIn: "すでにアクセスをお持ちですか？ログイン",
    research: "カテゴリの分析",
    moreInCategory: "このカテゴリのほかのニーズ",
    embedTitle: "カテゴリのパルス",
    topPain: "最大のペイン",
    needsOne: "{n}件のニーズ",
    needsFew: "{n}件のニーズ",
    needsMany: "{n}件のニーズ",
    allNeedsOne: "{n}件のニーズをすべて見る",
    allNeedsFew: "{n}件のニーズをすべて見る",
    allNeedsMany: "{n}件のニーズをすべて見る",
    about: "算出方法",
    aboutSample: "サンプルは、各カテゴリの人気アプリ約100本について、App Storeの最新レビュー最大500件です。各ニーズはカテゴリのすべてのレビューから探し、一致したレビューの一部を手作業で確認しています（正確さ80%以上）。",
    aboutScore: "「ペイン」は1〜10の目安のスコアです。半分はそのことに触れたレビューがカテゴリ内で占める割合、30%はそうしたレビューの総数、20%はそれが見られるアプリの割合から算出します。検索需要や市場規模ではありません。",
    aboutLevels: "言葉で表すと：{scale}。",
    empty: "パルスはまだ集計中です",
    emptyBody: "レビューから集めた具体的なペインがまもなくここに表示されます。",
    noResults: "見つかりませんでした",
    noResultsBody: "別のカテゴリや短いキーワードでお試しください。",
    pages: "ページ",
    next: "次へ",
    previous: "前へ",
  },
});

export type PulseStrings = (typeof pulseStrings)["ru"];
