import { defineStrings } from "@/site/i18n/strings";

// Web strings of «Пульс» (SPEC: app_04_inapp/Documentation/PulseDemand-2026-09-24/SPEC.md).
// Need titles and summaries come from content/v2/pulse-demand.json per locale; this table holds
// the interface only. Plural forms: *One / *Few / *Many follow pluralCategory() of
// src/site/i18n/translate.ts (en/de/fr: few = many = "other"; ja has one form).
export const pulseStrings = defineStrings({
  ru: {
    title: "Пульс",
    subtitle: "Что просят и на что жалуются в отзывах — и насколько это больно",
    metaDescription: "Конкретные просьбы и жалобы из отзывов App Store по категориям приложений: сколько людей об этом пишут и насколько это больно.",
    pain: "Боль",
    painAria: "Боль {score} из 10.",
    kindRequest: "Просят",
    kindPain: "Жалуются",
    filterAll: "Все",
    filterRequest: "Просят",
    filterPain: "Жалуются",
    kindFilter: "Вид",
    category: "Категория",
    allCategories: "Все категории",
    search: "Поиск",
    searchPlaceholder: "Например, виджет или синхронизация",
    searchSubmit: "Найти",
    apply: "Показать",
    reset: "Сбросить",
    reviewsOne: "{n} отзыв",
    reviewsFew: "{n} отзыва",
    reviewsMany: "{n} отзывов",
    appsOne: "{n} приложение",
    appsFew: "{n} приложения",
    appsMany: "{n} приложений",
    inAppsOne: "в {n} из {total} приложения",
    inAppsFew: "в {n} из {total} приложений",
    inAppsMany: "в {n} из {total} приложений",
    shareOfCategory: "{share} отзывов категории",
    verified: "проверено вручную: {correct} из {sample}",
    ratingsTitle: "Оценки в этих отзывах",
    ratingAria: "{stars} из 5: {count}",
    rating: "Оценка {rating} из 5",
    topAppsTitle: "Чаще всего пишут в",
    evidenceTitle: "Что пишут",
    original: "Показать оригинал",
    lockedTitle: "Остальные цитаты — в Plus",
    lockedBody: "Они открываются вместе с разбором категории: с Plus или доступом к этой категории.",
    signIn: "Уже есть доступ? Войти",
    research: "Разбор категории",
    moreInCategory: "Ещё в категории",
    embedTitle: "Пульс категории",
    embedSubtitle: "Что просят и на что жалуются в отзывах этой категории.",
    embedAll: "Все потребности категории ({count})",
    allNeeds: "Все потребности ({count})",
    about: "Как считаем",
    aboutSample: "Выборка — до 500 последних отзывов у ~100 популярных приложений каждой категории в App Store. Каждую потребность ищем по всем отзывам категории, а совпадения выборочно проверяем вручную: точность не ниже 80%.",
    aboutScore: "«Боль» — условная оценка от 1 до 10: наполовину она зависит от доли отзывов категории, где об этом пишут, на 30% — от того, сколько таких отзывов всего, на 20% — от доли приложений, где это встречается. Это не поисковый спрос и не размер рынка.",
    empty: "Пульс ещё собирается",
    emptyBody: "Скоро здесь появятся конкретные просьбы и жалобы из отзывов.",
    noResults: "Ничего не нашли",
    noResultsBody: "Попробуй другую категорию, вид или более короткий запрос.",
    pages: "Страницы",
    next: "Дальше",
    previous: "Назад",
  },
  en: {
    title: "Pulse",
    subtitle: "What people ask for and complain about in app reviews — and how much it hurts",
    metaDescription: "Concrete requests and complaints from App Store reviews, by app category: how many people write about each one and how much it hurts.",
    pain: "Pain",
    painAria: "Pain {score} out of 10.",
    kindRequest: "Request",
    kindPain: "Complaint",
    filterAll: "All",
    filterRequest: "Requests",
    filterPain: "Complaints",
    kindFilter: "Type",
    category: "Category",
    allCategories: "All categories",
    search: "Search",
    searchPlaceholder: "For example, widget or sync",
    searchSubmit: "Search",
    apply: "Show",
    reset: "Reset",
    reviewsOne: "{n} review",
    reviewsFew: "{n} reviews",
    reviewsMany: "{n} reviews",
    appsOne: "{n} app",
    appsFew: "{n} apps",
    appsMany: "{n} apps",
    inAppsOne: "in {n} of {total} app",
    inAppsFew: "in {n} of {total} apps",
    inAppsMany: "in {n} of {total} apps",
    shareOfCategory: "{share} of the category’s reviews",
    verified: "hand-checked: {correct} of {sample}",
    ratingsTitle: "Ratings in these reviews",
    ratingAria: "{stars} out of 5: {count}",
    rating: "Rated {rating} out of 5",
    topAppsTitle: "Most often in",
    evidenceTitle: "What people write",
    original: "Show original",
    lockedTitle: "More quotes with Plus",
    lockedBody: "They open together with the category breakdown: with Plus or access to this category.",
    signIn: "Already have access? Sign in",
    research: "Category breakdown",
    moreInCategory: "More in this category",
    embedTitle: "Category pulse",
    embedSubtitle: "What people ask for and complain about in this category’s reviews.",
    embedAll: "All needs in this category ({count})",
    allNeeds: "All needs ({count})",
    about: "How we count",
    aboutSample: "The sample is up to 500 recent App Store reviews for each of about 100 popular apps per category. We look for each need across all of the category’s reviews and check a random sample of matches by hand: at least 80% are correct.",
    aboutScore: "“Pain” is a rough score from 1 to 10: half comes from the share of the category’s reviews that mention it, 30% from how many such reviews there are in total, 20% from the share of apps where it comes up. It is not search demand and not market size.",
    empty: "Pulse is still being gathered",
    emptyBody: "Concrete requests and complaints from reviews will appear here soon.",
    noResults: "Nothing found",
    noResultsBody: "Try another category, type or a shorter query.",
    pages: "Pages",
    next: "Next",
    previous: "Previous",
  },
  de: {
    title: "Puls",
    subtitle: "Was sich Menschen in App-Bewertungen wünschen und worüber sie klagen — und wie sehr es schmerzt",
    metaDescription: "Konkrete Wünsche und Beschwerden aus App-Store-Bewertungen, nach App-Kategorien: wie viele Menschen darüber schreiben und wie sehr es schmerzt.",
    pain: "Schmerz",
    painAria: "Schmerz {score} von 10.",
    kindRequest: "Wunsch",
    kindPain: "Beschwerde",
    filterAll: "Alle",
    filterRequest: "Wünsche",
    filterPain: "Beschwerden",
    kindFilter: "Art",
    category: "Kategorie",
    allCategories: "Alle Kategorien",
    search: "Suche",
    searchPlaceholder: "Zum Beispiel Widget oder Synchronisierung",
    searchSubmit: "Suchen",
    apply: "Anzeigen",
    reset: "Zurücksetzen",
    reviewsOne: "{n} Bewertung",
    reviewsFew: "{n} Bewertungen",
    reviewsMany: "{n} Bewertungen",
    appsOne: "{n} App",
    appsFew: "{n} Apps",
    appsMany: "{n} Apps",
    inAppsOne: "in {n} von {total} App",
    inAppsFew: "in {n} von {total} Apps",
    inAppsMany: "in {n} von {total} Apps",
    shareOfCategory: "{share} der Bewertungen der Kategorie",
    verified: "von Hand geprüft: {correct} von {sample}",
    ratingsTitle: "Sterne in diesen Bewertungen",
    ratingAria: "{stars} von 5: {count}",
    rating: "{rating} von 5 Sternen",
    topAppsTitle: "Am häufigsten bei",
    evidenceTitle: "Was Menschen schreiben",
    original: "Original anzeigen",
    lockedTitle: "Weitere Zitate mit Plus",
    lockedBody: "Sie werden zusammen mit der Analyse der Kategorie freigeschaltet: mit Plus oder Zugang zu dieser Kategorie.",
    signIn: "Schon Zugang? Anmelden",
    research: "Analyse der Kategorie",
    moreInCategory: "Mehr in dieser Kategorie",
    embedTitle: "Puls der Kategorie",
    embedSubtitle: "Was sich Menschen in den Bewertungen dieser Kategorie wünschen und worüber sie klagen.",
    embedAll: "Alle Bedürfnisse der Kategorie ({count})",
    allNeeds: "Alle Bedürfnisse ({count})",
    about: "So zählen wir",
    aboutSample: "Die Stichprobe umfasst bis zu 500 aktuelle App-Store-Bewertungen von jeweils rund 100 beliebten Apps pro Kategorie. Jedes Bedürfnis suchen wir in allen Bewertungen der Kategorie und prüfen eine Zufallsauswahl der Treffer von Hand: Mindestens 80 % sind korrekt.",
    aboutScore: "„Schmerz“ ist ein grober Wert von 1 bis 10: zur Hälfte der Anteil der Bewertungen der Kategorie, die es erwähnen, zu 30 % die Gesamtzahl solcher Bewertungen, zu 20 % der Anteil der Apps, in denen es vorkommt. Das ist weder Suchnachfrage noch Marktgröße.",
    empty: "Der Puls wird noch gesammelt",
    emptyBody: "Hier erscheinen bald konkrete Wünsche und Beschwerden aus Bewertungen.",
    noResults: "Nichts gefunden",
    noResultsBody: "Versuch eine andere Kategorie, Art oder eine kürzere Suche.",
    pages: "Seiten",
    next: "Weiter",
    previous: "Zurück",
  },
  fr: {
    title: "Pouls",
    subtitle: "Ce que les gens demandent et ce dont ils se plaignent dans les avis d’apps — et à quel point ça fait mal",
    metaDescription: "Demandes et plaintes concrètes tirées des avis de l’App Store, par catégorie d’apps : combien de personnes en parlent et à quel point ça fait mal.",
    pain: "Douleur",
    painAria: "Douleur {score} sur 10.",
    kindRequest: "Demande",
    kindPain: "Plainte",
    filterAll: "Tout",
    filterRequest: "Demandes",
    filterPain: "Plaintes",
    kindFilter: "Type",
    category: "Catégorie",
    allCategories: "Toutes les catégories",
    search: "Recherche",
    searchPlaceholder: "Par exemple, widget ou synchronisation",
    searchSubmit: "Rechercher",
    apply: "Afficher",
    reset: "Réinitialiser",
    reviewsOne: "{n} avis",
    reviewsFew: "{n} avis",
    reviewsMany: "{n} avis",
    appsOne: "{n} appli",
    appsFew: "{n} applis",
    appsMany: "{n} applis",
    inAppsOne: "dans {n} appli sur {total}",
    inAppsFew: "dans {n} applis sur {total}",
    inAppsMany: "dans {n} applis sur {total}",
    shareOfCategory: "{share} des avis de la catégorie",
    verified: "vérifié à la main : {correct} sur {sample}",
    ratingsTitle: "Notes dans ces avis",
    ratingAria: "{stars} sur 5 : {count}",
    rating: "Note : {rating} sur 5",
    topAppsTitle: "Le plus souvent dans",
    evidenceTitle: "Ce que les gens écrivent",
    original: "Voir l’original",
    lockedTitle: "Plus de citations avec Plus",
    lockedBody: "Elles s’ouvrent avec l’analyse de la catégorie : avec Plus ou un accès à cette catégorie.",
    signIn: "Déjà un accès ? Se connecter",
    research: "Analyse de la catégorie",
    moreInCategory: "Aussi dans cette catégorie",
    embedTitle: "Pouls de la catégorie",
    embedSubtitle: "Ce que les gens demandent et ce dont ils se plaignent dans les avis de cette catégorie.",
    embedAll: "Tous les besoins de la catégorie ({count})",
    allNeeds: "Tous les besoins ({count})",
    about: "Comment on compte",
    aboutSample: "L’échantillon compte jusqu’à 500 avis récents de l’App Store pour environ 100 apps populaires par catégorie. Nous cherchons chaque besoin dans tous les avis de la catégorie et vérifions à la main un échantillon des correspondances : au moins 80 % sont justes.",
    aboutScore: "La « douleur » est une note indicative de 1 à 10 : la moitié vient de la part des avis de la catégorie qui en parlent, 30 % du nombre total de ces avis, 20 % de la part des apps où cela revient. Ce n’est ni la demande de recherche ni la taille du marché.",
    empty: "Le pouls est encore en cours de collecte",
    emptyBody: "Des demandes et plaintes concrètes tirées des avis apparaîtront bientôt ici.",
    noResults: "Aucun résultat",
    noResultsBody: "Essaie une autre catégorie, un autre type ou une recherche plus courte.",
    pages: "Pages",
    next: "Suivant",
    previous: "Précédent",
  },
  ja: {
    title: "パルス",
    subtitle: "アプリのレビューで求められていること、不満に思われていること — そしてその痛みの強さ",
    metaDescription: "App Storeのレビューから、アプリのカテゴリごとに具体的な要望と不満をまとめました。どれくらいの人が書いているか、どれほど痛いかがわかります。",
    pain: "ペイン",
    painAria: "ペイン 10段階中{score}。",
    kindRequest: "要望",
    kindPain: "不満",
    filterAll: "すべて",
    filterRequest: "要望",
    filterPain: "不満",
    kindFilter: "種類",
    category: "カテゴリ",
    allCategories: "すべてのカテゴリ",
    search: "検索",
    searchPlaceholder: "例：ウィジェット、同期",
    searchSubmit: "検索",
    apply: "表示",
    reset: "リセット",
    reviewsOne: "{n}件のレビュー",
    reviewsFew: "{n}件のレビュー",
    reviewsMany: "{n}件のレビュー",
    appsOne: "{n}アプリ",
    appsFew: "{n}アプリ",
    appsMany: "{n}アプリ",
    inAppsOne: "{total}アプリ中{n}アプリ",
    inAppsFew: "{total}アプリ中{n}アプリ",
    inAppsMany: "{total}アプリ中{n}アプリ",
    shareOfCategory: "カテゴリのレビューの{share}",
    verified: "手作業で確認：{sample}件中{correct}件が正確",
    ratingsTitle: "これらのレビューの評価",
    ratingAria: "星{stars}：{count}件",
    rating: "評価 {rating}/5",
    topAppsTitle: "よく書かれているアプリ",
    evidenceTitle: "レビューの声",
    original: "原文を表示",
    lockedTitle: "残りの引用はPlusで",
    lockedBody: "カテゴリの分析と一緒に開放されます。Plus またはこのカテゴリへのアクセスが必要です。",
    signIn: "すでにアクセスをお持ちですか？ログイン",
    research: "カテゴリの分析",
    moreInCategory: "このカテゴリのほかのニーズ",
    embedTitle: "カテゴリのパルス",
    embedSubtitle: "このカテゴリのレビューで求められていること、不満に思われていること。",
    embedAll: "このカテゴリのすべてのニーズ（{count}）",
    allNeeds: "すべてのニーズ（{count}）",
    about: "算出方法",
    aboutSample: "サンプルは、各カテゴリの人気アプリ約100本について、App Storeの最新レビュー最大500件です。各ニーズはカテゴリのすべてのレビューから探し、一致したレビューの一部を手作業で確認しています（正確さ80%以上）。",
    aboutScore: "「ペイン」は1〜10の目安のスコアです。半分はそのことに触れたレビューがカテゴリ内で占める割合、30%はそうしたレビューの総数、20%はそれが見られるアプリの割合から算出します。検索需要や市場規模ではありません。",
    empty: "パルスはまだ集計中です",
    emptyBody: "レビューから集めた具体的な要望と不満がまもなくここに表示されます。",
    noResults: "見つかりませんでした",
    noResultsBody: "別のカテゴリや種類、短いキーワードでお試しください。",
    pages: "ページ",
    next: "次へ",
    previous: "前へ",
  },
});

export type PulseStrings = (typeof pulseStrings)["ru"];
