import "dotenv/config";
import { readFileSync } from "node:fs";
import { prisma } from "../src/lib/prisma";
import type { StoredSummary, SummaryProse, OpportunityType } from "../src/lib/summarize";

// Apply hand-authored bilingual cards to prod. Input: cards.json — an array of
// entries shaped like the StoredSummary on disk (language-neutral scalars flat,
// ru/en prose blocks). We validate each entry, then write Product.summary. We do
// NOT touch summaryHash: these are Claude-authored, never regenerated by the
// YandexGPT script, so the hash is irrelevant to them.
//
//   DATABASE_URL=file:/opt/badcomment/data/prod.db npx tsx scripts/apply-cards.ts cards.json

const TYPES: OpportunityType[] = [
  "design",
  "features",
  "reliability",
  "pricing",
  "content",
  "support",
];

type Entry = {
  id: string;
  opportunityType: OpportunityType;
  cloneable: boolean;
  buildability: number;
  profit: number;
  ru: SummaryProse;
  en: SummaryProse;
};

function badProse(p: unknown, lang: string, id: string): string | null {
  if (!p || typeof p !== "object") return `${id}: missing ${lang} block`;
  const o = p as Record<string, unknown>;
  if (typeof o.tagline !== "string" || !o.tagline.trim()) return `${id}: ${lang}.tagline empty`;
  if (typeof o.verdict !== "string" || !o.verdict.trim()) return `${id}: ${lang}.verdict empty`;
  if (!Array.isArray(o.gaps)) return `${id}: ${lang}.gaps not array`;
  for (const g of o.gaps as Record<string, unknown>[]) {
    if (!g || typeof g.title !== "string" || !g.title.trim()) return `${id}: ${lang} gap missing title`;
  }
  return null;
}

function validate(e: Entry): string | null {
  if (!e.id) return "entry missing id";
  if (!TYPES.includes(e.opportunityType)) return `${e.id}: bad opportunityType ${e.opportunityType}`;
  if (typeof e.buildability !== "number" || e.buildability < 1 || e.buildability > 5)
    return `${e.id}: buildability out of range`;
  if (typeof e.profit !== "number" || e.profit < 1 || e.profit > 5)
    return `${e.id}: profit out of range`;
  if (typeof e.cloneable !== "boolean") return `${e.id}: cloneable not boolean`;
  return badProse(e.ru, "ru", e.id) ?? badProse(e.en, "en", e.id);
}

async function run() {
  const path = process.argv[2] ?? "cards.json";
  const entries: Entry[] = JSON.parse(readFileSync(path, "utf8"));

  // Validate everything up front — never write a partial/garbage batch.
  const errors = entries.map(validate).filter((x): x is string => x != null);
  if (errors.length) {
    console.error(`VALIDATION FAILED (${errors.length}):`);
    for (const e of errors) console.error("  " + e);
    process.exit(1);
  }

  let ok = 0,
    missing = 0;
  for (const e of entries) {
    const product = await prisma.product.findUnique({ where: { id: e.id }, select: { id: true } });
    if (!product) {
      missing++;
      console.error(`MISSING product ${e.id}`);
      continue;
    }
    const stored: StoredSummary = {
      opportunityType: e.opportunityType,
      cloneable: e.cloneable,
      buildability: e.buildability,
      profit: e.profit,
      ru: e.ru,
      en: e.en,
    };
    await prisma.product.update({
      where: { id: e.id },
      data: { summary: JSON.stringify(stored) },
    });
    ok++;
  }

  console.log(`applied ${ok}/${entries.length}${missing ? `, ${missing} missing` : ""}`);
  await prisma.$disconnect();
}

run().catch(async (err) => {
  console.error(err);
  await prisma.$disconnect();
  process.exit(1);
});
