import { defineStrings } from "../../i18n/strings";

// Web-only strings of «Отзывы» — the review archive (/<L>/reviews, /<L>/reviews/<niche>,
// /<L>/reviews/<niche>/<app id>). Review texts are App Store originals (English); topic names
// are data in ru/en, so de/fr/ja pages print the English ones under `dataNote`. Category names
// are the rating's (sitedata/reviews.ts, each with its own nameLang): the 35 launch topics have
// de/fr/ja names, the others stay English — hence «some categories» in dataNote. The app UI keys the
// pages render through t() are listed in ./keys.ts; `appReviews*` / `nicheReviews*` label the
// rows the rating pages link here with (redesign spec §7.2 W5, W6).
// Word forms: "one|few|many|other" (src/site/i18n/count.ts). The methodology page has its own
// table (./methodology.ts). Voice: informal «ты» / du / tu; Japanese です・ます.

export const reviewsStrings = defineStrings({
  ru: {
    // Archive
    metaTitle: "Отзывы по темам",
    metaDescription: "{reviews} о {apps}: категории, приложения, полные тексты и темы каждого отзыва.",
    aboutAppsWord: "приложении|приложениях|приложениях|приложениях",
    title: "Отзывы",
    // Describes the pages below without a second instruction next to the «Выбери тему» head.
    subtitle: "Полный список отзывов о каждом приложении: оценка, исходный текст и все темы, которые в нём упомянуты.",
    dataNote: "",
    nichesWord: "категория|категории|категорий|категории",
    appsWord: "приложение|приложения|приложений|приложения",
    reviewsWord: "отзыв|отзыва|отзывов|отзыва",
    // = methodologyStrings.title (the row is named after the page it opens).
    methodology: "Как мы превращаем отзывы в выводы",
    methodologyBody: "Корпус, темы и ограничения разметки",
    locked: "В Plus",
    freeBadge: "Открыто бесплатно",
    // Category
    nicheMetaTitle: "Отзывы: {name}",
    nicheMetaDescription: "Категория «{name}»: {apps} и {reviews} с оценками и темами каждого текста.",
    appSearch: "Приложение или тема",
    topicsWord: "тема|темы|тем|темы",
    lockTitle: "Архив отзывов — в Plus",
    lockBody:
      "{apps} и {reviews} этой категории уже здесь: полный текст, оценка и темы каждого отзыва. Plus открывает весь архив и остальные разделы inApp.",
    lockSample: "Сначала посмотреть открытую категорию «{free}»",
    lockAppBody:
      "{reviews} о «{app}» уже здесь: полный текст, оценка и темы каждого отзыва. Plus открывает весь архив и остальные разделы inApp.",
    // App
    appMetaTitle: "{app}: размеченные отзывы",
    appMetaDescription: "{reviews} о «{app}» с оценками и темами каждого текста.",
    topicLabel: "Тема отзыва",
    topicSearch: "Найти тему",
    topicPickerOpen: "Выбрать тему: {name}",
    allTopics: "Все темы ({n})",
    ratingLabel: "Оценка",
    allRatings: "Все оценки",
    textSearch: "Поиск по тексту",
    worstFirst: "Сначала 1★",
    bestFirst: "Сначала 5★",
    listTitle: "Отзывы",
    loadingAll: "Загружаю полный список…",
    loadFailed: "Не удалось загрузить весь список — показаны первые отзывы. Обнови страницу, чтобы попробовать ещё раз.",
    showMore: "Показать ещё — осталось {n}",
    stars: "Оценка {n} из 5",
    // The rating pill's accessible name: it contains the visible «3★» (label in name).
    ratingPill: "Оценка: {stars}",
    // A picker / menu option with its count.
    optionCount: "{label} — {n}",
    emptyBody: "Попробуй другое слово или сбрось тему и оценку.",
    // Rows on the rating pages (W5 app page, W6 niche page)
    appReviewsTitle: "Все отзывы о приложении",
    appReviewsBody: "Полные тексты, оценки и темы каждого отзыва",
    nicheReviewsTitle: "Отзывы этой темы",
    nicheReviewsBody: "Полные тексты с оценками и темами каждого отзыва",
  },
  en: {
    metaTitle: "Reviews by topic",
    metaDescription: "{reviews} of {apps}: categories, apps, complete texts and the topics of every review.",
    aboutAppsWord: "app|apps|apps|apps",
    title: "Reviews",
    subtitle: "The complete review list of every app: the rating, the source text and every topic it mentions.",
    dataNote: "",
    nichesWord: "category|categories|categories|categories",
    appsWord: "app|apps|apps|apps",
    reviewsWord: "review|reviews|reviews|reviews",
    methodology: "How reviews become findings",
    methodologyBody: "The corpus, the topics and the limits of the labels",
    locked: "In Plus",
    freeBadge: "Free to read",
    nicheMetaTitle: "Reviews: {name}",
    nicheMetaDescription: "{name}: {apps} and {reviews} with ratings and the topics of every text.",
    appSearch: "App or topic",
    topicsWord: "topic|topics|topics|topics",
    lockTitle: "The review archive is part of Plus",
    lockBody:
      "{apps} and {reviews} in this category are right here: the complete text, rating and topics of every review. Plus opens the whole archive and the rest of inApp.",
    lockSample: "First, look at the open category: {free}",
    lockAppBody:
      "{reviews} of “{app}” are right here: the complete text, rating and topics of every review. Plus opens the whole archive and the rest of inApp.",
    appMetaTitle: "{app}: labelled reviews",
    appMetaDescription: "{reviews} of “{app}” with ratings and the topics of every text.",
    topicLabel: "Review topic",
    topicSearch: "Find a topic",
    topicPickerOpen: "Pick a topic: {name}",
    allTopics: "All topics ({n})",
    ratingLabel: "Rating",
    allRatings: "All ratings",
    textSearch: "Search the text",
    worstFirst: "1★ first",
    bestFirst: "5★ first",
    listTitle: "Reviews",
    loadingAll: "Loading the complete list…",
    loadFailed: "Couldn’t load the complete list — showing the first reviews. Reload the page to try again.",
    showMore: "Show more — {n} left",
    stars: "Rated {n} out of 5",
    ratingPill: "Rating: {stars}",
    optionCount: "{label} — {n}",
    emptyBody: "Try another word or reset the topic and the rating.",
    appReviewsTitle: "All reviews of this app",
    appReviewsBody: "Full texts, ratings and topics of every review",
    nicheReviewsTitle: "Reviews in this topic",
    nicheReviewsBody: "Full texts with the rating and topics of every review",
  },
  de: {
    metaTitle: "Rezensionen nach Themen",
    metaDescription: "{reviews} zu {apps}: Kategorien, Apps, vollständige Texte und die Themen jeder Rezension.",
    aboutAppsWord: "App|Apps|Apps|Apps",
    title: "Rezensionen",
    subtitle:
      "Die vollständige Liste der Rezensionen zu jeder App: die Bewertung, der Originaltext und alle Themen, die darin vorkommen.",
    dataNote: "Die Namen der Themen und mancher Kategorien sind auf Englisch, die Rezensionen im Original.",
    nichesWord: "Kategorie|Kategorien|Kategorien|Kategorien",
    appsWord: "App|Apps|Apps|Apps",
    reviewsWord: "Rezension|Rezensionen|Rezensionen|Rezensionen",
    methodology: "Wie aus Rezensionen Erkenntnisse werden",
    methodologyBody: "Korpus, Themen und Grenzen der Kennzeichnung",
    locked: "In Plus",
    freeBadge: "Kostenlos lesbar",
    nicheMetaTitle: "Rezensionen: {name}",
    nicheMetaDescription: "{name}: {apps} und {reviews} mit Bewertungen und den Themen jedes Textes.",
    appSearch: "App oder Thema",
    topicsWord: "Thema|Themen|Themen|Themen",
    lockTitle: "Das Rezensionsarchiv gehört zu Plus",
    lockBody:
      "{apps} und {reviews} dieser Kategorie liegen schon hier: der vollständige Text, die Bewertung und die Themen jeder Rezension. Plus öffnet das ganze Archiv und den Rest von inApp.",
    lockSample: "Schau dir zuerst die offene Kategorie an: {free}",
    lockAppBody:
      "{reviews} zu „{app}“ liegen schon hier: der vollständige Text, die Bewertung und die Themen jeder Rezension. Plus öffnet das ganze Archiv und den Rest von inApp.",
    appMetaTitle: "{app}: gekennzeichnete Rezensionen",
    appMetaDescription: "{reviews} zu „{app}“ mit Bewertungen und den Themen jedes Textes.",
    topicLabel: "Thema der Rezension",
    topicSearch: "Thema finden",
    topicPickerOpen: "Thema wählen: {name}",
    allTopics: "Alle Themen ({n})",
    ratingLabel: "Bewertung",
    allRatings: "Alle Bewertungen",
    textSearch: "Im Text suchen",
    worstFirst: "1★ zuerst",
    bestFirst: "5★ zuerst",
    listTitle: "Rezensionen",
    loadingAll: "Die vollständige Liste wird geladen…",
    loadFailed:
      "Die vollständige Liste ließ sich nicht laden — hier sind die ersten Rezensionen. Lade die Seite neu, um es noch einmal zu versuchen.",
    showMore: "Mehr anzeigen — noch {n}",
    stars: "Bewertet mit {n} von 5",
    ratingPill: "Bewertung: {stars}",
    optionCount: "{label} — {n}",
    emptyBody: "Versuch es mit einem anderen Wort oder setz Thema und Bewertung zurück.",
    appReviewsTitle: "Alle Rezensionen zu dieser App",
    appReviewsBody: "Volltexte, Bewertungen und Themen jeder Rezension",
    nicheReviewsTitle: "Rezensionen in diesem Thema",
    nicheReviewsBody: "Volltexte mit Bewertung und Themen jeder Rezension",
  },
  fr: {
    metaTitle: "Avis par thème",
    metaDescription: "{reviews} sur {apps} : catégories, apps, textes complets et thèmes de chaque avis.",
    aboutAppsWord: "app|apps|apps|apps",
    title: "Avis",
    subtitle: "La liste complète des avis sur chaque app : la note, le texte d’origine et tous les thèmes qu’il mentionne.",
    dataNote: "Les noms des thèmes et de certaines catégories sont en anglais, les avis dans leur langue d’origine.",
    nichesWord: "catégorie|catégories|catégories|catégories",
    appsWord: "app|apps|apps|apps",
    reviewsWord: "avis|avis|avis|avis",
    methodology: "Comment les avis deviennent des conclusions",
    methodologyBody: "Le corpus, les thèmes et les limites de l’annotation",
    locked: "Dans Plus",
    freeBadge: "En accès libre",
    nicheMetaTitle: "Avis : {name}",
    nicheMetaDescription: "{name} : {apps} et {reviews} avec les notes et les thèmes de chaque texte.",
    appSearch: "App ou thème",
    topicsWord: "thème|thèmes|thèmes|thèmes",
    lockTitle: "Les archives d’avis font partie de Plus",
    lockBody:
      "{apps} et {reviews} de cette catégorie sont déjà là : le texte complet, la note et les thèmes de chaque avis. Plus ouvre toutes les archives et le reste d’inApp.",
    lockSample: "D’abord, regarde la catégorie ouverte : {free}",
    lockAppBody:
      "{reviews} sur « {app} » sont déjà là : le texte complet, la note et les thèmes de chaque avis. Plus ouvre toutes les archives et le reste d’inApp.",
    appMetaTitle: "{app} : avis étiquetés",
    appMetaDescription: "{reviews} sur « {app} » avec les notes et les thèmes de chaque texte.",
    topicLabel: "Thème de l’avis",
    topicSearch: "Trouver un thème",
    topicPickerOpen: "Choisir un thème : {name}",
    allTopics: "Tous les thèmes ({n})",
    ratingLabel: "Note",
    allRatings: "Toutes les notes",
    textSearch: "Chercher dans le texte",
    worstFirst: "1★ d’abord",
    bestFirst: "5★ d’abord",
    listTitle: "Avis",
    loadingAll: "Chargement de la liste complète…",
    loadFailed: "Impossible de charger la liste complète ; voici les premiers avis. Recharge la page pour réessayer.",
    showMore: "Afficher plus — encore {n}",
    stars: "Noté {n} sur 5",
    ratingPill: "Note : {stars}",
    optionCount: "{label} — {n}",
    emptyBody: "Essaie un autre mot ou réinitialise le thème et la note.",
    appReviewsTitle: "Tous les avis sur cette app",
    appReviewsBody: "Textes complets, notes et thèmes de chaque avis",
    nicheReviewsTitle: "Avis de ce thème",
    nicheReviewsBody: "Textes complets avec la note et les thèmes de chaque avis",
  },
  ja: {
    metaTitle: "テーマ別のレビュー",
    metaDescription: "{apps}の{reviews}：カテゴリー、アプリ、全文、各レビューのテーマ。",
    aboutAppsWord: "アプリ",
    title: "レビュー",
    subtitle: "アプリごとのレビューの全リストです。評価、原文、本文で触れられているすべてのテーマがそろっています。",
    dataNote: "テーマと一部のカテゴリーの名前は英語、レビューは原文のままです。",
    nichesWord: "カテゴリー",
    appsWord: "アプリ",
    reviewsWord: "件のレビュー",
    methodology: "レビューが結論になるまで",
    methodologyBody: "コーパス、トピック、ラベル付けの限界",
    locked: "Plus",
    freeBadge: "無料公開",
    nicheMetaTitle: "レビュー：{name}",
    nicheMetaDescription: "{name}：{apps}と{reviews}。評価と各本文のテーマ付き。",
    appSearch: "アプリまたはテーマ",
    topicsWord: "テーマ",
    lockTitle: "レビューのアーカイブはPlusに含まれます",
    lockBody:
      "このカテゴリーの{apps}と{reviews}はすでにここにあります。各レビューの全文、評価、テーマを読めます。Plusでアーカイブ全体とinAppのほかのセクションが開きます。",
    lockSample: "まず公開中のカテゴリーを見る：{free}",
    lockAppBody:
      "{app}の{reviews}はすでにここにあります。各レビューの全文、評価、テーマを読めます。Plusでアーカイブ全体とinAppのほかのセクションが開きます。",
    appMetaTitle: "{app}：ラベル付きレビュー",
    appMetaDescription: "{app}の{reviews}。評価と各本文のテーマ付き。",
    topicLabel: "レビューのテーマ",
    topicSearch: "トピックを探す",
    topicPickerOpen: "テーマを選ぶ：{name}",
    allTopics: "すべてのテーマ（{n}）",
    ratingLabel: "評価",
    allRatings: "すべての評価",
    textSearch: "本文を検索",
    worstFirst: "★1から",
    bestFirst: "★5から",
    listTitle: "レビュー",
    loadingAll: "全リストを読み込んでいます…",
    loadFailed: "全リストを読み込めませんでした。最初のレビューを表示しています。もう一度試すにはページを再読み込みしてください。",
    showMore: "さらに表示（残り{n}件）",
    stars: "5段階中{n}の評価",
    ratingPill: "評価：{stars}",
    optionCount: "{label}（{n}）",
    emptyBody: "別の言葉で探すか、テーマと評価の絞り込みを解除してください。",
    appReviewsTitle: "このアプリのすべてのレビュー",
    appReviewsBody: "各レビューの全文、評価、トピック",
    nicheReviewsTitle: "このテーマのレビュー",
    nicheReviewsBody: "各レビューの全文、評価、トピック",
  },
});

export type ReviewsStrings = (typeof reviewsStrings)["ru"];
