import { defineStrings } from "../../i18n/strings";

// Web-only strings of the Plus paywall (/<L>/plus, the sheet, the welcome replay's last page)
// and the payment return page (/<L>/library?checkout=). App strings (title, description, plan
// row, disclosure, CTA, «Остаться с бесплатным разбором») come from content/v2/<L>/ui.json. The
// app's StoreKit wording is replaced by the web's YooKassa facts (spec 03 §2.7, spec 09 G11).
// Voice: «ты» / du / tu; Japanese です・ます like ui.ja.json (no いただく / ご〜ください).
// The return-page banners keep the old site's meaning (spec 06 §4.2).
//
// These strings mention web payment methods, so they never ride along with every page: the
// sheet receives them with its offer (GET /api/site/plus/offer), and only the pages that sell
// or confirm (/plus, /welcome, /library) render them on the server.

export const plusStrings = defineStrings({
  ru: {
    payNote:
      "Оплата в рублях — банковской картой или через СБП, через ЮKassa. Доступ включится сам, как только оплата подтвердится.",
    signInFirst: "Перед оплатой попросим войти — доступ привяжется к твоему аккаунту.",
    methodTitle: "Как оплатить?",
    methodCard: "Банковская карта",
    methodSbp: "СБП",
    errAlreadyActive: "В этом аккаунте Plus уже открыт.",
    errUnavailable: "Оплата сейчас недоступна. Попробуй чуть позже.",
    errFailed: "Не удалось создать платёж. Попробуй ещё раз.",
    errNetwork: "Нет соединения. Проверь интернет и попробуй ещё раз.",
    restore: "Войти, чтобы восстановить доступ",
    offerLink: "Оферта",
    supportLink: "Поддержка",
    legalLabel: "Документы и поддержка",
    iphoneTitle: "Приложение для iPhone",
    iphoneNote:
      "Plus можно купить и в приложении для iPhone. Покупки работают в одном аккаунте inApp: войди в приложении и на сайте одним способом — доступ откроется и там, и там.",
    appOnlyTitle: "Plus — в приложении для iPhone",
    appOnlyBody:
      "Plus оформляется в приложении inApp через App Store. Потом войди в приложении (Настройки → Аккаунт) и на сайте одним способом — Plus откроется и здесь.",
    appOnlyCta: "Открыть в App Store",
    pageDescription: "Все разборы и идеи inApp целиком, новые выпуски и экспорт материалов.",
    returnTitle: "Оплата Plus",
    returnDescription: "Подтверждение оплаты inApp Plus.",
    checking: "Проверяем оплату…",
    confirmed: "Оплата подтверждена. Полный доступ открыт.",
    failed: "Оплата не завершена. Деньги не списаны.",
    delayed: "Подтверждение задерживается. Доступ включится автоматически; можно обновить страницу через минуту.",
    signinNeeded: "Войди в аккаунт, с которого была оплата, — и мы проверим платёж.",
    missing: "Не нашли этот платёж в твоём аккаунте. Если деньги списались — напиши в поддержку.",
    doneTitle: "Plus открыт",
    doneLead: "Все разборы и идеи уже доступны. Приятного чтения!",
    openResearch: "Открыть разборы",
    tryAgain: "Попробовать ещё раз",
    refresh: "Обновить страницу",
    signIn: "Войти",
  },
  en: {
    payNote:
      "You pay in Russian roubles by bank card or SBP via YooKassa. Access turns on by itself as soon as the payment is confirmed.",
    signInFirst: "We’ll ask you to sign in before paying, so access is linked to your account.",
    methodTitle: "How would you like to pay?",
    methodCard: "Bank card",
    methodSbp: "SBP",
    errAlreadyActive: "Plus is already active on this account.",
    errUnavailable: "Payments aren’t available right now. Try again a bit later.",
    errFailed: "Couldn’t create the payment. Try again.",
    errNetwork: "No connection. Check your internet and try again.",
    restore: "Sign in to restore access",
    offerLink: "Public offer",
    supportLink: "Support",
    legalLabel: "Documents and support",
    iphoneTitle: "The iPhone app",
    iphoneNote:
      "You can also get Plus in the iPhone app. Purchases work across one inApp account: sign in the same way in the app and on the website, and your access opens in both.",
    appOnlyTitle: "Plus is in the iPhone app",
    appOnlyBody:
      "Get Plus in the inApp app through the App Store. Then sign in the same way in the app (Settings → Account) and on the website, and Plus opens here too.",
    appOnlyCta: "Open in the App Store",
    pageDescription: "Every inApp breakdown and idea in full, new releases and material export.",
    returnTitle: "Plus payment",
    returnDescription: "inApp Plus payment confirmation.",
    checking: "Confirming payment…",
    confirmed: "Payment confirmed. You now have full access.",
    failed: "Payment wasn’t completed. You weren’t charged.",
    delayed: "Confirmation is taking longer than usual. Access will activate automatically; refresh in a minute.",
    signinNeeded: "Sign in with the account you paid from, and we’ll check the payment.",
    missing: "We couldn’t find this payment on your account. If you were charged, contact support.",
    doneTitle: "Plus is unlocked",
    doneLead: "Every breakdown and idea is now available. Enjoy the reading!",
    openResearch: "Open breakdowns",
    tryAgain: "Try again",
    refresh: "Refresh the page",
    signIn: "Sign in",
  },
  de: {
    payNote:
      "Du zahlst in Rubel per Bankkarte oder SBP über YooKassa. Der Zugang wird automatisch freigeschaltet, sobald die Zahlung bestätigt ist.",
    signInFirst: "Vor dem Bezahlen bitten wir dich, dich anzumelden — so wird der Zugang mit deinem Konto verknüpft.",
    methodTitle: "Wie möchtest du bezahlen?",
    methodCard: "Bankkarte",
    methodSbp: "SBP",
    errAlreadyActive: "In diesem Konto ist Plus bereits aktiv.",
    errUnavailable: "Bezahlen ist gerade nicht möglich. Versuch es etwas später noch einmal.",
    errFailed: "Die Zahlung konnte nicht erstellt werden. Versuch es noch einmal.",
    errNetwork: "Keine Verbindung. Prüf dein Internet und versuch es noch einmal.",
    restore: "Anmelden, um den Zugang wiederherzustellen",
    offerLink: "Öffentliches Angebot",
    supportLink: "Support",
    legalLabel: "Dokumente und Support",
    iphoneTitle: "Die iPhone-App",
    iphoneNote:
      "Plus gibt es auch in der iPhone-App. Käufe gelten für ein inApp-Konto: Melde dich in der App und auf der Website auf dieselbe Weise an, dann ist dein Zugang überall offen.",
    appOnlyTitle: "Plus gibt es in der iPhone-App",
    appOnlyBody:
      "Hol dir Plus in der inApp-App über den App Store. Melde dich danach in der App (Einstellungen → Konto) und auf der Website auf dieselbe Weise an – dann ist Plus auch hier offen.",
    appOnlyCta: "Im App Store öffnen",
    pageDescription: "Alle Analysen und Ideen von inApp komplett, neue Ausgaben und Material-Export.",
    returnTitle: "Plus-Zahlung",
    returnDescription: "Zahlungsbestätigung für inApp Plus.",
    checking: "Zahlung wird geprüft…",
    confirmed: "Zahlung bestätigt. Der volle Zugang ist freigeschaltet.",
    failed: "Die Zahlung wurde nicht abgeschlossen. Es wurde nichts abgebucht.",
    delayed:
      "Die Bestätigung dauert länger als üblich. Der Zugang wird automatisch freigeschaltet; lade die Seite in einer Minute neu.",
    signinNeeded: "Melde dich mit dem Konto an, mit dem du bezahlt hast — dann prüfen wir die Zahlung.",
    missing: "Diese Zahlung haben wir in deinem Konto nicht gefunden. Falls Geld abgebucht wurde, schreib dem Support.",
    doneTitle: "Plus ist freigeschaltet",
    doneLead: "Alle Analysen und Ideen stehen dir jetzt offen. Viel Spaß beim Lesen!",
    openResearch: "Analysen öffnen",
    tryAgain: "Noch einmal versuchen",
    refresh: "Seite neu laden",
    signIn: "Anmelden",
  },
  fr: {
    payNote:
      "Tu paies en roubles par carte bancaire ou par SBP via YooKassa. L’accès s’active tout seul dès que le paiement est confirmé.",
    signInFirst: "On te demandera de te connecter avant de payer : l’accès sera lié à ton compte.",
    methodTitle: "Comment veux-tu payer ?",
    methodCard: "Carte bancaire",
    methodSbp: "SBP",
    errAlreadyActive: "Plus est déjà actif sur ce compte.",
    errUnavailable: "Le paiement n’est pas disponible pour le moment. Réessaie un peu plus tard.",
    errFailed: "Impossible de créer le paiement. Réessaie.",
    errNetwork: "Pas de connexion. Vérifie ton accès à Internet et réessaie.",
    restore: "Se connecter pour restaurer l’accès",
    offerLink: "Offre publique",
    supportLink: "Assistance",
    legalLabel: "Documents et assistance",
    iphoneTitle: "L’app iPhone",
    iphoneNote:
      "Tu peux aussi prendre Plus dans l’app iPhone. Les achats valent pour un seul compte inApp : connecte-toi de la même façon dans l’app et sur le site, et ton accès s’ouvre partout.",
    appOnlyTitle: "Plus est dans l’app iPhone",
    appOnlyBody:
      "Prends Plus dans l’app inApp via l’App Store. Connecte-toi ensuite de la même façon dans l’app (Réglages → Compte) et sur le site : Plus s’ouvrira ici aussi.",
    appOnlyCta: "Ouvrir dans l’App Store",
    pageDescription: "Tous les décryptages et toutes les idées d’inApp en entier, les nouveaux numéros et l’export des contenus.",
    returnTitle: "Paiement Plus",
    returnDescription: "Confirmation du paiement inApp Plus.",
    checking: "Vérification du paiement…",
    confirmed: "Paiement confirmé. L’accès complet est activé.",
    failed: "Le paiement n’a pas abouti. Tu n’as pas été débité.",
    delayed:
      "La confirmation prend plus de temps que d’habitude. L’accès s’activera automatiquement ; actualise la page dans une minute.",
    signinNeeded: "Connecte-toi avec le compte utilisé pour payer, et on vérifie le paiement.",
    missing: "On n’a pas trouvé ce paiement sur ton compte. Si tu as été débité, écris à l’assistance.",
    doneTitle: "Plus est débloqué",
    doneLead: "Tous les décryptages et toutes les idées sont maintenant disponibles. Bonne lecture !",
    openResearch: "Ouvrir les décryptages",
    tryAgain: "Réessayer",
    refresh: "Actualiser la page",
    signIn: "Se connecter",
  },
  ja: {
    payNote:
      "お支払いはロシア・ルーブルで、YooKassaを通じて銀行カードまたはSBPで行います。支払いが確認されると、アクセスは自動で有効になります。",
    signInFirst: "お支払いの前にログインしてください。アクセスはあなたのアカウントに紐づきます。",
    methodTitle: "お支払い方法",
    methodCard: "銀行カード",
    methodSbp: "SBP",
    errAlreadyActive: "このアカウントではPlusがすでに有効です。",
    errUnavailable: "現在お支払いは利用できません。しばらくしてからお試しください。",
    errFailed: "支払いを作成できませんでした。もう一度お試しください。",
    errNetwork: "接続できません。インターネット接続を確認して、もう一度お試しください。",
    restore: "ログインしてアクセスを復元",
    offerLink: "ウェブ決済の規約",
    supportLink: "サポート",
    legalLabel: "規約とサポート",
    iphoneTitle: "iPhoneアプリ",
    iphoneNote:
      "PlusはiPhoneアプリでも購入できます。購入は1つのinAppアカウントで共通です。アプリとサイトで同じ方法でサインインすると、どちらでも使えるようになります。",
    appOnlyTitle: "PlusはiPhoneアプリで",
    appOnlyBody:
      "PlusはinAppアプリ内でApp Storeから購入できます。購入後、アプリ（設定 → アカウント）とサイトで同じ方法でサインインすると、ここでもPlusが使えます。",
    appOnlyCta: "App Storeで開く",
    pageDescription: "inAppのすべての分析とアイデア、新しい号、資料のエクスポート。",
    returnTitle: "Plusのお支払い",
    returnDescription: "inApp Plusのお支払い確認。",
    checking: "お支払いを確認しています…",
    confirmed: "お支払いが確認されました。フルアクセスが有効になりました。",
    failed: "お支払いは完了しませんでした。料金は請求されていません。",
    delayed: "確認に時間がかかっています。アクセスは自動で有効になります。1分ほどしてからページを再読み込みしてください。",
    signinNeeded: "お支払いに使ったアカウントでログインしてください。支払いを確認します。",
    missing: "このお支払いはあなたのアカウントで見つかりませんでした。料金が請求された場合はサポートに連絡してください。",
    doneTitle: "Plusが有効になりました",
    doneLead: "すべての分析とアイデアを読めるようになりました。どうぞお楽しみください。",
    openResearch: "分析を開く",
    tryAgain: "もう一度試す",
    refresh: "ページを再読み込み",
    signIn: "ログイン",
  },
});

export type PlusStrings = (typeof plusStrings)["ru"];
