import { defineStrings } from "../../i18n/strings";

// Web-only strings of the Plus paywall (/<L>/plus + the sheet) and the payment return page
// (/<L>/library?checkout=). App strings (title, plan detail, CTA, disclosure) come from
// content/v2/<L>/ui.json. The app's StoreKit wording is replaced by the web's YooKassa facts
// (spec 03 §2.7, spec 09 G11). Voice: «ты» / du / tu; Japanese です・ます like ui.ja.json.
// The return-page banners keep the old site's meaning (spec 06 §4.2).

export const plusStrings = defineStrings({
  ru: {
    planTitle: "Plus навсегда",
    topicsOne: "{n} разбор",
    topicsFew: "{n} разбора",
    topicsMany: "{n} разборов",
    topicsOther: "{n} разбора",
    benefitTopics: "{topics} целиком — с находками и цитатами из отзывов",
    benefitIdeas: "{ideas} с подробностями",
    benefitExport: "Экспорт материалов в документ",
    benefitUpdates: "Новые выпуски — без доплат",
    benefitsLabel: "Что открывает Plus",
    payNote:
      "Оплата в рублях — банковской картой или через СБП, через ЮKassa. Доступ включится сам, как только оплата подтвердится.",
    signInFirst: "Перед оплатой попросим войти — доступ привяжется к твоему аккаунту.",
    methodTitle: "Как оплатить?",
    methodCard: "Банковская карта",
    methodSbp: "СБП",
    errAlreadyActive: "В этом аккаунте Plus уже открыт.",
    errUnavailable: "Оплата сейчас недоступна. Попробуй чуть позже.",
    errFailed: "Не удалось создать платёж. Попробуй ещё раз.",
    errNetwork: "Нет соединения. Проверь интернет и попробуй ещё раз.",
    restore: "Войти, чтобы восстановить доступ",
    offerLink: "Оферта",
    supportLink: "Поддержка",
    legalLabel: "Документы и поддержка",
    iphoneTitle: "Приложение для iPhone",
    iphoneNote:
      "В приложении для iPhone Plus оформляется отдельно, через App Store. Покупка на сайте и подписка в App Store не связаны и не восстанавливаются друг через друга.",
    pageDescription: "Все разборы и идеи inApp целиком, новые выпуски и экспорт материалов.",
    returnTitle: "Оплата Plus",
    returnDescription: "Подтверждение оплаты inApp Plus.",
    checking: "Проверяем оплату…",
    confirmed: "Оплата подтверждена. Полный доступ открыт.",
    failed: "Оплата не завершена. Деньги не списаны.",
    delayed: "Подтверждение задерживается. Доступ включится автоматически; можно обновить страницу через минуту.",
    signinNeeded: "Войди в аккаунт, с которого была оплата, — и мы проверим платёж.",
    missing: "Не нашли этот платёж в твоём аккаунте. Если деньги списались — напиши в поддержку.",
    doneTitle: "Plus открыт",
    doneLead: "Все разборы и идеи уже доступны. Приятного чтения!",
    openResearch: "Открыть разборы",
    tryAgain: "Попробовать ещё раз",
    refresh: "Обновить страницу",
    signIn: "Войти",
  },
  en: {
    planTitle: "Plus for life",
    topicsOne: "{n} breakdown",
    topicsFew: "{n} breakdowns",
    topicsMany: "{n} breakdowns",
    topicsOther: "{n} breakdowns",
    benefitTopics: "{topics} in full — with findings and review quotes",
    benefitIdeas: "{ideas} with all the details",
    benefitExport: "Export any material to a document",
    benefitUpdates: "New releases at no extra cost",
    benefitsLabel: "What Plus unlocks",
    payNote:
      "You pay in Russian roubles by bank card or SBP via YooKassa. Access turns on by itself as soon as the payment is confirmed.",
    signInFirst: "We’ll ask you to sign in before paying, so access is linked to your account.",
    methodTitle: "How would you like to pay?",
    methodCard: "Bank card",
    methodSbp: "SBP",
    errAlreadyActive: "Plus is already active on this account.",
    errUnavailable: "Payments aren’t available right now. Try again a bit later.",
    errFailed: "Couldn’t create the payment. Try again.",
    errNetwork: "No connection. Check your internet and try again.",
    restore: "Sign in to restore access",
    offerLink: "Payment offer",
    supportLink: "Support",
    legalLabel: "Documents and support",
    iphoneTitle: "The iPhone app",
    iphoneNote:
      "In the iPhone app, Plus is bought separately through the App Store. A purchase on the website and an App Store subscription aren’t linked and can’t be restored from one another.",
    pageDescription: "Every inApp breakdown and idea in full, new releases and material export.",
    returnTitle: "Plus payment",
    returnDescription: "inApp Plus payment confirmation.",
    checking: "Confirming payment…",
    confirmed: "Payment confirmed. Full access is open.",
    failed: "Payment wasn’t completed. You weren’t charged.",
    delayed: "Confirmation is taking longer than usual. Access will activate automatically; refresh in a minute.",
    signinNeeded: "Sign in with the account you paid from, and we’ll check the payment.",
    missing: "We couldn’t find this payment on your account. If you were charged, contact support.",
    doneTitle: "Plus is open",
    doneLead: "Every breakdown and idea is now available. Enjoy the reading!",
    openResearch: "Open breakdowns",
    tryAgain: "Try again",
    refresh: "Refresh the page",
    signIn: "Sign in",
  },
  de: {
    planTitle: "Plus für immer",
    topicsOne: "{n} Analyse",
    topicsFew: "{n} Analysen",
    topicsMany: "{n} Analysen",
    topicsOther: "{n} Analysen",
    benefitTopics: "{topics} komplett – mit Erkenntnissen und Zitaten aus Bewertungen",
    benefitIdeas: "{ideas} mit allen Details",
    benefitExport: "Export von Materialien als Dokument",
    benefitUpdates: "Neue Ausgaben ohne Aufpreis",
    benefitsLabel: "Was Plus freischaltet",
    payNote:
      "Du zahlst in Rubel per Bankkarte oder SBP über YooKassa. Der Zugang wird automatisch freigeschaltet, sobald die Zahlung bestätigt ist.",
    signInFirst: "Vor dem Bezahlen bitten wir dich, dich anzumelden – so wird der Zugang mit deinem Konto verknüpft.",
    methodTitle: "Wie möchtest du bezahlen?",
    methodCard: "Bankkarte",
    methodSbp: "SBP",
    errAlreadyActive: "In diesem Konto ist Plus bereits aktiv.",
    errUnavailable: "Bezahlen ist gerade nicht möglich. Versuch es etwas später noch einmal.",
    errFailed: "Die Zahlung konnte nicht erstellt werden. Versuch es noch einmal.",
    errNetwork: "Keine Verbindung. Prüf dein Internet und versuch es noch einmal.",
    restore: "Anmelden, um den Zugang wiederherzustellen",
    offerLink: "Zahlungsangebot",
    supportLink: "Support",
    legalLabel: "Dokumente und Support",
    iphoneTitle: "Die iPhone-App",
    iphoneNote:
      "In der iPhone-App wird Plus separat über den App Store abgeschlossen. Ein Kauf auf der Website und ein App-Store-Abo sind nicht verknüpft und lassen sich nicht gegenseitig wiederherstellen.",
    pageDescription: "Alle Analysen und Ideen von inApp komplett, neue Ausgaben und Material-Export.",
    returnTitle: "Plus-Zahlung",
    returnDescription: "Zahlungsbestätigung für inApp Plus.",
    checking: "Zahlung wird geprüft…",
    confirmed: "Zahlung bestätigt. Der volle Zugang ist freigeschaltet.",
    failed: "Die Zahlung wurde nicht abgeschlossen. Es wurde nichts abgebucht.",
    delayed:
      "Die Bestätigung dauert länger als üblich. Der Zugang wird automatisch freigeschaltet; lade die Seite in einer Minute neu.",
    signinNeeded: "Melde dich mit dem Konto an, mit dem du bezahlt hast – dann prüfen wir die Zahlung.",
    missing: "Diese Zahlung haben wir in deinem Konto nicht gefunden. Falls Geld abgebucht wurde, schreib dem Support.",
    doneTitle: "Plus ist freigeschaltet",
    doneLead: "Alle Analysen und Ideen stehen dir jetzt offen. Viel Spaß beim Lesen!",
    openResearch: "Analysen öffnen",
    tryAgain: "Noch einmal versuchen",
    refresh: "Seite neu laden",
    signIn: "Anmelden",
  },
  fr: {
    planTitle: "Plus à vie",
    topicsOne: "{n} décryptage",
    topicsFew: "{n} décryptages",
    topicsMany: "{n} décryptages",
    topicsOther: "{n} décryptages",
    benefitTopics: "{topics} en entier – constats et citations d’avis compris",
    benefitIdeas: "{ideas} avec tous les détails",
    benefitExport: "Export des contenus en document",
    benefitUpdates: "Les nouveaux numéros sans supplément",
    benefitsLabel: "Ce que Plus débloque",
    payNote:
      "Tu paies en roubles par carte bancaire ou par SBP via YooKassa. L’accès s’active tout seul dès que le paiement est confirmé.",
    signInFirst: "On te demandera de te connecter avant de payer : l’accès sera lié à ton compte.",
    methodTitle: "Comment veux-tu payer ?",
    methodCard: "Carte bancaire",
    methodSbp: "SBP",
    errAlreadyActive: "Plus est déjà actif sur ce compte.",
    errUnavailable: "Le paiement n’est pas disponible pour le moment. Réessaie un peu plus tard.",
    errFailed: "Impossible de créer le paiement. Réessaie.",
    errNetwork: "Pas de connexion. Vérifie ton accès à Internet et réessaie.",
    restore: "Se connecter pour restaurer l’accès",
    offerLink: "Offre de paiement",
    supportLink: "Assistance",
    legalLabel: "Documents et assistance",
    iphoneTitle: "L’app iPhone",
    iphoneNote:
      "Dans l’app iPhone, Plus s’achète séparément via l’App Store. Un achat sur le site et un abonnement App Store ne sont pas liés et ne se restaurent pas l’un par l’autre.",
    pageDescription: "Tous les décryptages et toutes les idées d’inApp en entier, les nouveaux numéros et l’export des contenus.",
    returnTitle: "Paiement Plus",
    returnDescription: "Confirmation du paiement inApp Plus.",
    checking: "Vérification du paiement…",
    confirmed: "Paiement confirmé. L’accès complet est ouvert.",
    failed: "Le paiement n’a pas abouti. Tu n’as pas été débité.",
    delayed:
      "La confirmation prend plus de temps que d’habitude. L’accès s’activera automatiquement ; actualise la page dans une minute.",
    signinNeeded: "Connecte-toi avec le compte utilisé pour payer, et on vérifie le paiement.",
    missing: "On n’a pas trouvé ce paiement sur ton compte. Si tu as été débité, écris à l’assistance.",
    doneTitle: "Plus est ouvert",
    doneLead: "Tous les décryptages et toutes les idées sont maintenant disponibles. Bonne lecture !",
    openResearch: "Ouvrir les décryptages",
    tryAgain: "Réessayer",
    refresh: "Actualiser la page",
    signIn: "Se connecter",
  },
  ja: {
    planTitle: "Plus 買い切り",
    topicsOne: "{n}件の分析",
    topicsFew: "{n}件の分析",
    topicsMany: "{n}件の分析",
    topicsOther: "{n}件の分析",
    benefitTopics: "{topics}をすべて — 発見とレビューの引用つき",
    benefitIdeas: "{ideas}の詳細",
    benefitExport: "資料をドキュメントに書き出し",
    benefitUpdates: "新しい号も追加料金なし",
    benefitsLabel: "Plusで開くもの",
    payNote:
      "お支払いはロシア・ルーブルで、YooKassaを通じて銀行カードまたはSBPで行います。支払いが確認されると、アクセスは自動で有効になります。",
    signInFirst: "お支払いの前にログインしていただきます。アクセスはあなたのアカウントに紐づきます。",
    methodTitle: "お支払い方法",
    methodCard: "銀行カード",
    methodSbp: "SBP",
    errAlreadyActive: "このアカウントではPlusがすでに有効です。",
    errUnavailable: "現在お支払いをご利用いただけません。しばらくしてからお試しください。",
    errFailed: "支払いを作成できませんでした。もう一度お試しください。",
    errNetwork: "接続できません。インターネット接続を確認して、もう一度お試しください。",
    restore: "ログインしてアクセスを復元",
    offerLink: "支払いに関する規約",
    supportLink: "サポート",
    legalLabel: "規約とサポート",
    iphoneTitle: "iPhoneアプリ",
    iphoneNote:
      "iPhoneアプリのPlusは、App Storeで別途ご購入いただけます。サイトでの購入とApp Storeのサブスクリプションは連携しておらず、相互に復元することはできません。",
    pageDescription: "inAppのすべての分析とアイデア、新しい号、資料のエクスポート。",
    returnTitle: "Plusのお支払い",
    returnDescription: "inApp Plusのお支払い確認。",
    checking: "お支払いを確認しています…",
    confirmed: "お支払いが確認されました。フルアクセスが有効になりました。",
    failed: "お支払いは完了しませんでした。料金は請求されていません。",
    delayed: "確認に時間がかかっています。アクセスは自動で有効になります。1分ほどしてからページを再読み込みしてください。",
    signinNeeded: "お支払いに使ったアカウントでログインしてください。支払いを確認します。",
    missing: "このお支払いはあなたのアカウントで見つかりませんでした。料金が請求された場合はサポートにご連絡ください。",
    doneTitle: "Plusが有効になりました",
    doneLead: "すべての分析とアイデアを読めるようになりました。どうぞお楽しみください。",
    openResearch: "分析を開く",
    tryAgain: "もう一度試す",
    refresh: "ページを再読み込み",
    signIn: "ログイン",
  },
});

export type PlusStrings = (typeof plusStrings)["ru"];
