import { defineStrings } from "../i18n/strings";

// Web-only strings of the shell (header, tab bar, footer, "open in app" banner).
// App strings (tab titles «Разборы/Идеи/Сохранённое», «Настройки», «Язык», legal links)
// come from the app packs through t(); only web wording lives here.
// `rating` holds the app's «Рейтинги» values (content/v2/<L>/ui.json) verbatim: that key is not
// in SHELL_UI_KEYS (i18n/builtin.ts), and the section nav and the footer read it from here.

export const shellStrings = defineStrings({
  ru: {
    pulse: "Пульс",
    signIn: "Войти",
    signOut: "Выйти",
    signOutFailed: "Не получилось выйти. Попробуй ещё раз.",
    account: "Аккаунт",
    plusActive: "Plus активен",
    home: "inApp — на главную",
    mainNav: "Основная навигация",
    footerNav: "Навигация по сайту",
    skipToContent: "Перейти к содержимому",
    oldSite: "Старая версия сайта",
    paymentOffer: "Публичная оферта",
    bannerSubLive: "Разборы и идеи всегда под рукой",
    bannerCtaSoon: "Подробнее",
    bannerCtaLive: "Открыть",
    bannerDismiss: "Скрыть",
    notFoundBody: "Вернись в каталог и выбери другой материал.",
    rating: "Рейтинги",
    reviews: "Отзывы",
    mcp: "MCP",
    sectionsNav: "Разделы сайта",
    sectionsMore: "Ещё разделы",
    menu: "Меню",
  },
  en: {
    pulse: "Pulse",
    signIn: "Sign in",
    signOut: "Sign out",
    signOutFailed: "Couldn’t sign out. Try again.",
    account: "Account",
    plusActive: "Plus is active",
    home: "inApp — home",
    mainNav: "Main navigation",
    footerNav: "Site navigation",
    skipToContent: "Skip to content",
    oldSite: "Previous version of the site",
    paymentOffer: "Public offer",
    bannerSubLive: "Breakdowns and ideas in your pocket",
    bannerCtaSoon: "Learn more",
    bannerCtaLive: "Open",
    bannerDismiss: "Dismiss",
    notFoundBody: "Go back to the catalog and pick another material.",
    rating: "Ratings",
    reviews: "Reviews",
    mcp: "MCP",
    sectionsNav: "Site sections",
    sectionsMore: "More sections",
    menu: "Menu",
  },
  de: {
    pulse: "Puls",
    signIn: "Anmelden",
    signOut: "Abmelden",
    signOutFailed: "Abmelden hat nicht geklappt. Versuch es noch einmal.",
    account: "Konto",
    plusActive: "Plus ist aktiv",
    home: "inApp — Startseite",
    mainNav: "Hauptnavigation",
    footerNav: "Seitennavigation",
    skipToContent: "Zum Inhalt springen",
    oldSite: "Frühere Version der Website",
    paymentOffer: "Öffentliches Angebot",
    bannerSubLive: "Analysen und Ideen immer dabei",
    bannerCtaSoon: "Mehr erfahren",
    bannerCtaLive: "Öffnen",
    bannerDismiss: "Ausblenden",
    notFoundBody: "Geh zurück in den Katalog und wähl ein anderes Material.",
    rating: "Bewertungen",
    reviews: "Rezensionen",
    mcp: "MCP",
    sectionsNav: "Bereiche der Website",
    sectionsMore: "Weitere Bereiche",
    menu: "Menü",
  },
  fr: {
    pulse: "Pouls",
    signIn: "Se connecter",
    signOut: "Se déconnecter",
    signOutFailed: "Impossible de se déconnecter. Réessaie.",
    account: "Compte",
    plusActive: "Plus est actif",
    home: "inApp — accueil",
    mainNav: "Navigation principale",
    footerNav: "Navigation du site",
    skipToContent: "Aller au contenu",
    oldSite: "Ancienne version du site",
    paymentOffer: "Offre publique",
    bannerSubLive: "Décryptages et idées toujours à portée de main",
    bannerCtaSoon: "En savoir plus",
    bannerCtaLive: "Ouvrir",
    bannerDismiss: "Masquer",
    notFoundBody: "Reviens au catalogue et choisis un autre contenu.",
    rating: "Classements",
    reviews: "Avis",
    mcp: "MCP",
    sectionsNav: "Rubriques du site",
    sectionsMore: "Autres rubriques",
    menu: "Menu",
  },
  ja: {
    pulse: "パルス",
    signIn: "ログイン",
    signOut: "ログアウト",
    signOutFailed: "ログアウトできませんでした。もう一度お試しください。",
    account: "アカウント",
    plusActive: "Plusは有効です",
    home: "inAppホーム",
    mainNav: "メインナビゲーション",
    footerNav: "サイトナビゲーション",
    skipToContent: "本文へスキップ",
    oldSite: "旧バージョンのサイト",
    paymentOffer: "ウェブ決済の規約",
    bannerSubLive: "分析とアイデアをいつでも手元に",
    bannerCtaSoon: "詳しく見る",
    bannerCtaLive: "開く",
    bannerDismiss: "閉じる",
    notFoundBody: "カタログに戻って別の資料を選んでください。",
    rating: "評価一覧",
    reviews: "レビュー",
    mcp: "MCP",
    sectionsNav: "サイトのセクション",
    sectionsMore: "ほかのセクション",
    menu: "メニュー",
  },
});

/** One locale's row of shellStrings (client: useWeb<ShellStrings>("shell")). */
export type ShellStrings = (typeof shellStrings)["ru"];
