// Client-safe URL helpers for the pre-built WebP artwork in public/media
// (generated by scripts/v2/export-images.mjs; spec 04 §6.3).
// Do not use next/image optimization for these files: the widths already exist.

import type { Art } from "./types";

export const MEDIA_BASE = "/media";

/** `sizes` for full-width reader/catalogue artwork (≤ 680 px column). */
export const MEDIA_SIZES_ARTICLE = "(min-width: 720px) 680px, 100vw";

function url(art: Art, width: number): string {
  return `${MEDIA_BASE}/${art.src}-${width}.webp`;
}

/**
 * URL of the variant closest to `width`: the smallest available width that is
 * ≥ `width` (no visible upscaling), else the largest one. Without `width` the
 * largest variant is returned.
 */
export function mediaSrc(art: Art, width?: number): string {
  const widths = [...art.widths].sort((a, b) => a - b);
  if (widths.length === 0) throw new Error(`Art "${art.src}" has no widths`);
  if (width === undefined) return url(art, widths[widths.length - 1]);
  const pick = widths.find((w) => w >= width) ?? widths[widths.length - 1];
  return url(art, pick);
}

/** `srcset` with every available width: "/media/x-480.webp 480w, /media/x-800.webp 800w, …". */
export function mediaSrcSet(art: Art): string {
  return [...art.widths]
    .sort((a, b) => a - b)
    .map((w) => `${url(art, w)} ${w}w`)
    .join(", ");
}

/** Absolute URL of the largest variant (Open Graph images). */
export function mediaAbsoluteUrl(art: Art, siteUrl: string, width?: number): string {
  return new URL(mediaSrc(art, width), siteUrl).toString();
}
